/* PÁGINA PÚBLICA
 * Aquí se reúne el catálogo, los banners, los socios, los indicadores y la historia.
 * Presenta los puntos de atención, las cotizaciones y los canales de contacto.
 */
const productList = document.querySelector('#product-list');
const productSelect = document.querySelector('#product-select');
const kpiList = document.querySelector('#kpi-list');
let catalogProducts = [];
let catalogCategories = [];
const catalogProductsByCategory = new Map();
let catalogCategoryLoading = null;
let selectedCatalogCategoryId = null;
let whatsappNumber = '';
let timelineItems = [];
let activeTimelineItem = 0;
let bannerItems = [];
let activeBannerItem = 0;
let bannerTimer = null;
let commercialPartners = [];
let commercialPartnersTimer = null;
let attentionPoints = [];
let companyContactPhone = '';
let analyticsEnabled = false;
let analyticsSession = '';
// Escapo el contenido de la API antes de insertarlo en plantillas HTML.
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character]));

// Identifica cada visita con una sesión local y registra eventos solo si la medición está habilitada.
function getAnalyticsSession() { try { const key = 'costa_grande_analytics_session'; let value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID().replace(/-/g, ''); localStorage.setItem(key, value); } return value; } catch { return ''; } }
function trackAnalytics(type, details = {}) { if (!analyticsEnabled || !analyticsSession) return; fetch('/api/analytics/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, session: analyticsSession, path: location.pathname, ...details }), keepalive: true }).catch(() => {}); }
async function loadAnalyticsConfiguration() { const response = await fetch('/api/analytics/config'); const configuration = await response.json(); analyticsEnabled = Boolean(configuration.enabled); if (analyticsEnabled) { analyticsSession = getAnalyticsSession(); trackAnalytics('visita_web'); } }

// Abre WhatsApp con el mensaje preparado y avisa si todavía no hay un número configurado.
function contactByWhatsApp(message) {
  if (!whatsappNumber) { alert('No hay número de WhatsApp configurado. Comunícate con la empresa por sus canales de atención.'); return; }
  window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, '_blank', 'noopener');
}

// Muestra únicamente los canales de contacto que la empresa haya configurado.
function renderSocialNetworks(settings) { const networks = [[['social-facebook','header-social-facebook'], settings.facebookUrl], [['social-instagram','header-social-instagram'], settings.instagramUrl], [['social-linkedin','header-social-linkedin'], settings.linkedinUrl]]; let configured = 0; networks.forEach(([ids, url]) => { const visible = Boolean(url); ids.forEach((id) => { const link = document.querySelector(`#${id}`); if (!link) return; link.classList.toggle('hidden', !visible); if (visible) link.href = url; else link.removeAttribute('href'); }); if (visible) configured += 1; }); const note = document.querySelector('#social-networks-note'); if (note) note.textContent = configured ? 'Síguenos en nuestras redes oficiales.' : 'Las cuentas oficiales se podrán enlazar cuando estén disponibles.'; }
function renderContactPhone(contactPhone) { const phone = String(contactPhone || '').trim(); const callNumber = phone.replace(/[^\d+]/g, ''); companyContactPhone = phone; ['attention-contact-phone', 'footer-contact-phone'].forEach((id) => { const container = document.querySelector(`#${id}`); if (!container) return; const link = container.querySelector('a'); container.classList.toggle('hidden', !phone); if (phone) { link.textContent = phone; link.href = `tel:${callNumber}`; } else { link.textContent = ''; link.removeAttribute('href'); } }); if (attentionPoints.length) renderAttentionPoints(); }
function renderContactEmail(contactEmail) { const email = String(contactEmail || '').trim(); const container = document.querySelector('#footer-contact-email'); if (!container) return; const link = container.querySelector('a'); container.classList.toggle('hidden', !email); if (email) { link.textContent = email; link.href = `mailto:${email}`; } else { link.textContent = ''; link.removeAttribute('href'); } }
async function loadWhatsAppSettings() { const settings = await fetch('/api/company-settings').then((response) => response.json()); whatsappNumber = settings.whatsappNumber || ''; renderSocialNetworks(settings); renderContactPhone(settings.contactPhone); renderContactEmail(settings.contactEmail); }
// Actualiza la presentación, los principios institucionales y la imagen disponibles.
async function loadAbout() { const settings = await fetch('/api/about').then((response) => response.json()); const fields = [['about-description', settings.description], ['company-purpose', settings.purpose], ['company-mission', settings.mission], ['company-vision', settings.vision]]; fields.forEach(([id, value]) => { const element = document.querySelector(`#${id}`); if (element && value) element.textContent = value; }); const image = document.querySelector('#about-image'); if (image && settings.hasImage) image.src = '/api/about/image'; }
// Presenta la promoción solo cuando la API confirma que tiene una imagen.
function closePromotionalPopup(){const popup=document.querySelector('#promotional-popup');popup.classList.add('hidden');document.body.classList.remove('popup-open')}async function loadPromotionalPopup(){const response=await fetch('/api/promotional-popup');if(!response.ok)return;const popup=await response.json();if(!popup.hasImage)return;const modal=document.querySelector('#promotional-popup'),image=document.querySelector('#promotional-popup-image');image.src=`/api/promotional-popup/image?v=${Date.now()}`;modal.classList.remove('hidden');document.body.classList.add('popup-open');document.querySelector('#close-promotional-popup').focus()}document.querySelector('#close-promotional-popup').addEventListener('click',closePromotionalPopup);
// Abre las indicaciones externas con coordenadas cuando están disponibles y usa la dirección como respaldo.
function googleDirectionsUrl(point) { const hasCoordinates = point.latitude !== null && point.latitude !== '' && point.longitude !== null && point.longitude !== '' && Number.isFinite(Number(point.latitude)) && Number.isFinite(Number(point.longitude)); const destination = hasCoordinates ? `${point.latitude},${point.longitude}` : `${point.address}, Perú`; return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`; }
async function copyAttentionAddress(id) { const point = attentionPoints.find((item) => Number(item.id) === id); if (!point) return; try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(point.address); else { const field = document.createElement('textarea'); field.value = point.address; field.setAttribute('readonly', ''); field.style.position = 'fixed'; field.style.opacity = '0'; document.body.append(field); field.select(); document.execCommand('copy'); field.remove(); } const status = document.querySelector('#attention-copy-status'); status.textContent = `Dirección de ${point.name} copiada.`; const button = document.querySelector(`.attention-copy[data-id="${id}"]`); if (button) { button.classList.add('copied'); button.setAttribute('aria-label', 'Dirección copiada'); setTimeout(() => { button.classList.remove('copied'); button.setAttribute('aria-label', `Copiar dirección de ${point.name}`); }, 1800); } } catch { document.querySelector('#attention-copy-status').textContent = 'No fue posible copiar la dirección.'; } }
// Presenta los puntos como tarjetas independientes sin cargar un mapa dentro de la página.
function renderAttentionPoints() { const list = document.querySelector('#attention-list'); const callNumber = companyContactPhone.replace(/[^\d+]/g, ''); const phoneAction = callNumber ? `<a class="attention-meta-button" href="tel:${callNumber}" aria-label="Llamar al ${escapeHtml(companyContactPhone)}" title="Llamar"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.7 3.8 9 3.2l1.7 4.4-1.8 1.3a14.3 14.3 0 0 0 6.2 6.2l1.3-1.8 4.4 1.7-.6 2.3c-.3 1.1-1.4 1.8-2.5 1.6C10.1 17.7 6.3 13.9 5.1 6.3 4.9 5.2 5.6 4.1 6.7 3.8Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg></a>` : ''; list.innerHTML = attentionPoints.map((point) => `<article class="attention-point"><h3>${escapeHtml(point.name)}</h3><p class="attention-address">${escapeHtml(point.address)}</p><div class="attention-meta">${phoneAction}<span class="attention-schedule"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M12 7.5V12l3 2" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>${escapeHtml(point.schedule || '7am a 6pm')}</span></div><div class="attention-actions"><a class="attention-directions" href="${googleDirectionsUrl(point)}" target="_blank" rel="noopener">Cómo llegar</a><button class="attention-copy" data-id="${point.id}" type="button" aria-label="Copiar dirección de ${escapeHtml(point.name)}" title="Copiar dirección"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="7" width="10" height="12" rx="2" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M6 16H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2" fill="none" stroke="currentColor" stroke-width="1.7"/></svg></button></div></article>`).join('') || '<p class="attention-empty">No hay puntos de atención registrados.</p>'; list.querySelectorAll('.attention-copy').forEach((button) => button.addEventListener('click', () => copyAttentionAddress(Number(button.dataset.id)))); }
async function loadAttentionPoints() { attentionPoints = await fetch('/api/attention-points').then((response) => response.json()); renderAttentionPoints(); }
// Reinicia el carrusel al recibir banners y activa la rotación solo si hay varios.
async function loadBanners() { bannerItems = await fetch('/api/banners').then((response) => response.json()); activeBannerItem = 0; clearInterval(bannerTimer); renderBanner(); if (bannerItems.length > 1) bannerTimer = setInterval(() => moveBanner(1), 15000); }
function applyBannerFit(image) { const aspectRatio = image.naturalWidth / image.naturalHeight, usesCover = aspectRatio <= 2; image.classList.toggle('banner-slide-standard', usesCover); image.classList.toggle('banner-slide-wide', !usesCover); }
function renderBanner() { const slider = document.querySelector('#banner-slider'), numbers = document.querySelector('#banner-numbers'); const hasManyBanners = bannerItems.length > 1; if (!bannerItems.length) { slider.parentElement.classList.add('hidden'); return; } slider.parentElement.classList.remove('hidden'); const banner = bannerItems[activeBannerItem]; slider.innerHTML = `<img class="banner-slide" fetchpriority="high" decoding="async" src="/api/banners/${banner.id}/image" alt="Banner publicitario ${activeBannerItem + 1}">`; const bannerImage = slider.querySelector('.banner-slide'); if (bannerImage.complete && bannerImage.naturalWidth) applyBannerFit(bannerImage); else bannerImage.addEventListener('load', () => applyBannerFit(bannerImage), { once:true }); document.querySelectorAll('.banner-arrow').forEach((button) => { button.classList.toggle('hidden', !hasManyBanners); }); numbers.classList.toggle('hidden', !hasManyBanners); numbers.innerHTML = hasManyBanners ? bannerItems.map((_, index) => `<button class="banner-number ${index === activeBannerItem ? 'active' : ''}" type="button" aria-label="Ver banner ${index + 1}" aria-current="${index === activeBannerItem ? 'true' : 'false'}">${String(index + 1).padStart(2, '0')}</button>`).join('') : ''; numbers.querySelectorAll('.banner-number').forEach((button, index) => button.addEventListener('click', () => { activeBannerItem = index; renderBanner(); })); }
function moveBanner(direction) { if (bannerItems.length < 2) return; activeBannerItem = (activeBannerItem + direction + bannerItems.length) % bannerItems.length; renderBanner(); }
// Presenta los socios y desplazo sus tarjetas cuando no caben todas en la vista.
async function loadCommercialPartners() { commercialPartners = await fetch('/api/commercial-partners').then((response) => response.json()); const track = document.querySelector('#commercial-partners-track'); clearInterval(commercialPartnersTimer); if (!commercialPartners.length) { track.innerHTML = '<p class="partners-empty">Próximamente compartiremos a nuestros socios comerciales.</p>'; return; } const cards = commercialPartners.map((partner) => `<article class="commercial-partner"><img src="${partner.image}" alt="Logo de ${escapeHtml(partner.name)}"><span>${escapeHtml(partner.name)}</span></article>`).join(''); track.innerHTML = cards; const carousel = commercialPartners.length > 5; track.classList.toggle('is-carousel', carousel); if (carousel) commercialPartnersTimer = setInterval(() => { const maximum = track.scrollWidth - track.clientWidth; const atEnd = track.scrollLeft >= maximum - 4; track.scrollTo({ left: atEnd ? 0 : Math.min(track.scrollLeft + track.clientWidth / 2, maximum), behavior: 'smooth' }); }, 4000); }
// Inserta los indicadores y la historia con los textos que entrega la API.
async function loadKpis() { const kpis = await fetch('/api/kpis').then((response) => response.json()); kpiList.innerHTML = kpis.map((kpi) => `<article class="kpi-card"><span class="kpi-value">${escapeHtml(kpi.value)}</span><h3>${escapeHtml(kpi.title)}</h3><p>${escapeHtml(kpi.description || '')}</p></article>`).join(''); }
async function loadTimeline() { timelineItems = await fetch('/api/timeline').then((response) => response.json()); activeTimelineItem = 0; renderTimeline(); }
// Muestra el hito activo junto con una vista previa de los hitos vecinos.
function renderTimeline() { if (!timelineItems.length) return; const item = timelineItems[activeTimelineItem]; const previous = activeTimelineItem > 0 ? timelineItems[activeTimelineItem - 1] : null; const next = activeTimelineItem < timelineItems.length - 1 ? timelineItems[activeTimelineItem + 1] : null; const image = item.image ? `<img class="timeline-image" src="${item.image}" alt="${escapeHtml(item.title)}">` : ''; document.querySelector('#timeline-slider').innerHTML = `<article class="timeline-slide"><div class="timeline-side">${previous ? `<strong>${escapeHtml(previous.year)}</strong><p>${escapeHtml(previous.title)}</p>` : ''}</div><div class="timeline-featured ${image ? 'with-image' : ''}"><div><time>${escapeHtml(item.year)}</time><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.text)}</p></div>${image}</div><div class="timeline-side">${next ? `<strong>${escapeHtml(next.year)}</strong><p>${escapeHtml(next.title)}</p>` : ''}</div></article>`; document.querySelector('#timeline-dots').innerHTML = timelineItems.map((entry, index) => `<button class="timeline-dot ${index === activeTimelineItem ? 'active' : ''}" type="button" aria-label="Ver año ${escapeHtml(entry.year)}"></button>`).join(''); document.querySelector('#timeline-previous').disabled = !previous; document.querySelector('#timeline-next').disabled = !next; document.querySelectorAll('.timeline-dot').forEach((button, index) => button.addEventListener('click', () => { activeTimelineItem = index; renderTimeline(); })); }
function moveTimeline(direction) { const target = activeTimelineItem + direction; if (target < 0 || target >= timelineItems.length) return; activeTimelineItem = target; renderTimeline(); }
document.querySelector('#timeline-previous').addEventListener('click', () => moveTimeline(-1)); document.querySelector('#timeline-next').addEventListener('click', () => moveTimeline(1)); let timelineTouchStart = 0; document.querySelector('#timeline-slider').addEventListener('touchstart', (event) => { timelineTouchStart = event.changedTouches[0].screenX; }, { passive: true }); document.querySelector('#timeline-slider').addEventListener('touchend', (event) => { const distance = event.changedTouches[0].screenX - timelineTouchStart; if (Math.abs(distance) > 40) moveTimeline(distance < 0 ? 1 : -1); }, { passive: true });
document.querySelector('#banner-previous').addEventListener('click', () => moveBanner(-1)); document.querySelector('#banner-next').addEventListener('click', () => moveBanner(1));
document.querySelector('#whatsapp-general').addEventListener('click', () => { trackAnalytics('clic_whatsapp'); contactByWhatsApp('Hola, deseo comunicarme con atención comercial.'); });

// Mantiene el estado visual y accesible del menú móvil al abrirlo o seguir un enlace.
const mobileMenuToggle = document.querySelector('#mobile-menu-toggle');
const mainNavigation = document.querySelector('#main-navigation');
const mobileStoreFinder = document.createElement('a');
mobileStoreFinder.className = 'mobile-store-finder';
mobileStoreFinder.href = '#contacto';
mobileStoreFinder.textContent = 'Encuentra tu tienda ↗';
mainNavigation.insertBefore(mobileStoreFinder, document.querySelector('#session-menu'));
mobileMenuToggle.addEventListener('click', () => {
  const isOpen = mainNavigation.classList.toggle('is-open');
  mobileMenuToggle.classList.toggle('is-open', isOpen);
  mobileMenuToggle.setAttribute('aria-expanded', String(isOpen));
  mobileMenuToggle.setAttribute('aria-label', isOpen ? 'Cerrar menú' : 'Abrir menú');
});
mainNavigation.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => {
  mainNavigation.classList.remove('is-open'); mobileMenuToggle.classList.remove('is-open'); mobileMenuToggle.setAttribute('aria-expanded', 'false'); mobileMenuToggle.setAttribute('aria-label', 'Abrir menú');
}));

// Construye cada tarjeta de producto de catalogo con foto cuando existe y con un icono cuando falta.
function productCard(product){const visual=product.image&&(product.image.startsWith('data:image/')||product.image.startsWith('/media/'))?`<img class="product-photo" loading="lazy" decoding="async" src="${product.image}" alt="${escapeHtml(product.name)}">`:`<div class="product-icon">${escapeHtml(product.image||'📦')}</div>`;return `<article class="product product-card" tabindex="0">${visual}<div class="product-name"><h3>${escapeHtml(product.name)}</h3></div><div class="product-details"><p class="category">${escapeHtml(product.parentCategory?`${product.parentCategory} / ${product.category}`:product.category)}</p><p>${escapeHtml(product.description)}</p><button class="button select-product" data-product="${escapeHtml(product.name)}">Cotizar este producto</button><button class="text-button whatsapp-product" data-product="${escapeHtml(product.name)}">Consultar por WhatsApp</button></div></article>`}
function categoryCard(category){const visual=category.hasImage?`<img class="category-photo" loading="lazy" decoding="async" src="/api/catalog/categories/${category.id}/image" alt="${escapeHtml(category.name)}">`:`<div class="category-placeholder">${escapeHtml(category.name.slice(0,1).toUpperCase())}</div>`;const total=Number(category.productCount||0);return `<button class="catalog-category-card" type="button" data-category-id="${category.id}">${visual}<span><small>${total?`${total} ${total===1?'opción':'opciones'}`:'Explorar'}</small>${escapeHtml(category.name)}<b aria-hidden="true">→</b></span></button>`}
function scrollCatalogElement(selector,direction){const element=document.querySelector(selector);if(element)element.scrollBy({left:direction*element.clientWidth*.8,behavior:'smooth'})}
function keepProductsInView(){if(window.matchMedia('(max-width:700px)').matches)requestAnimationFrame(()=>productList.scrollIntoView({behavior:'smooth',block:'start'}))}
// Enlaza los controles después de cada renderizado del catálogo.
function bindCatalogInteractions(){document.querySelectorAll('.catalog-category-card,.catalog-filter').forEach(button=>button.addEventListener('click',()=>{selectedCatalogCategoryId=button.dataset.categoryId?Number(button.dataset.categoryId):null;const category=catalogCategories.find(item=>item.id===selectedCatalogCategoryId);if(category)trackAnalytics('categoria_abierta',{categoryId:category.id,categoryName:category.name});renderCatalog();if(category)keepProductsInView()}));document.querySelector('#catalog-previous')?.addEventListener('click',()=>scrollCatalogElement('#product-list',-1));document.querySelector('#catalog-next')?.addEventListener('click',()=>scrollCatalogElement('#product-list',1));document.querySelector('#catalog-filter-previous')?.addEventListener('click',()=>scrollCatalogElement('#catalog-filter-track',-1));document.querySelector('#catalog-filter-next')?.addEventListener('click',()=>scrollCatalogElement('#catalog-filter-track',1));document.querySelectorAll('.select-product').forEach(button=>button.addEventListener('click',()=>{trackAnalytics('producto_consultado',{productName:button.dataset.product});document.querySelector('.quote-product').value=button.dataset.product;document.querySelector('#cotizacion').scrollIntoView({behavior:'smooth'})}));document.querySelectorAll('.whatsapp-product').forEach(button=>button.addEventListener('click',()=>{trackAnalytics('clic_whatsapp',{productName:button.dataset.product});contactByWhatsApp(`Hola, deseo consultar por el producto: ${button.dataset.product}.`)}))}
// Cambia entre categorías y productos según el filtro seleccionado.
function renderCatalog(){const title=document.querySelector('#catalog-title'),navigation=document.querySelector('#catalog-navigation'),previous=document.querySelector('#catalog-previous'),next=document.querySelector('#catalog-next'),categories=catalogCategories,filters=[`<button class="catalog-filter ${selectedCatalogCategoryId===null?'active':''}" type="button">Todas las categorías</button>`,...categories.map(category=>`<button class="catalog-filter ${selectedCatalogCategoryId===category.id?'active':''}" type="button" data-category-id="${category.id}">${escapeHtml(category.name)}</button>`)].join(''),hasFilterCarousel=categories.length>8,hasCategoryCarousel=!selectedCatalogCategoryId&&categories.length>4;navigation.innerHTML=`<button id="catalog-filter-previous" class="catalog-filter-arrow ${hasFilterCarousel?'':'hidden'}" type="button" aria-label="Ver categorías anteriores">‹</button><div id="catalog-filter-track" class="catalog-filter-track ${hasFilterCarousel?'is-carousel':''}">${filters}</div><button id="catalog-filter-next" class="catalog-filter-arrow ${hasFilterCarousel?'':'hidden'}" type="button" aria-label="Ver más categorías">›</button>`;productList.classList.toggle('catalog-carousel',hasCategoryCarousel);productList.classList.toggle('catalog-grid',!hasCategoryCarousel);previous.classList.toggle('hidden',!hasCategoryCarousel);next.classList.toggle('hidden',!hasCategoryCarousel);if(!selectedCatalogCategoryId){title.innerHTML='Conoce nuestros <em>productos</em>';productList.innerHTML=categories.map(categoryCard).join('')||'<p>Aún no hay categorías registradas.</p>';bindCatalogInteractions();return}const category=catalogCategories.find(item=>item.id===selectedCatalogCategoryId);if(!category){selectedCatalogCategoryId=null;return renderCatalog()}title.textContent=category.name;const products=catalogProductsByCategory.get(category.id);if(!products){productList.innerHTML='<p>Cargando productos…</p>';loadCategoryProducts(category.id);return}productList.innerHTML=products.map(productCard).join('')||'<p>Esta categoría aún no tiene productos registrados.</p>';bindCatalogInteractions()}
// Consulta los productos de una categoría una sola vez y conserva el resultado para navegar más rápido.
async function loadCategoryProducts(categoryId){if(catalogProductsByCategory.has(categoryId)||catalogCategoryLoading===categoryId)return;catalogCategoryLoading=categoryId;try{const products=await fetch(`/api/catalog/categories/${categoryId}/products`).then(response=>response.json());catalogProductsByCategory.set(categoryId,products);if(selectedCatalogCategoryId===categoryId){renderCatalog();keepProductsInView()}}finally{catalogCategoryLoading=null}}
// Prepara las opciones de cotización y sincroniza la unidad del producto elegido.
function quoteOptions(selected=''){return `<option value="">Selecciona un producto</option>${catalogProducts.map(product=>`<option ${product.name===selected?'selected':''}>${escapeHtml(product.name)}</option>`).join('')}`}
function syncQuoteUnit(item){const product=catalogProducts.find(product=>product.name===item.querySelector('.quote-product').value);item.querySelector('.quote-unit').value=product?.unit||'—'}
// Conecta cada fila de cotización y deja siempre una fila disponible en el formulario.
function wireQuoteItem(item){item.querySelector('.remove-quote-item').addEventListener('click',()=>{const rows=document.querySelectorAll('.quote-item');if(rows.length===1){item.querySelector('.quote-product').value='';item.querySelector('.quote-quantity').value='1';syncQuoteUnit(item);return}item.remove()});item.querySelector('.quote-product').addEventListener('change',()=>syncQuoteUnit(item));syncQuoteUnit(item)}
function addQuoteItem(data={}){const item=document.createElement('div');item.className='quote-item';item.innerHTML=`<label>Producto<select class="quote-product" required>${quoteOptions(data.product||'')}</select></label><label>Cantidad<input class="quote-quantity" type="number" min="0.01" step="0.01" value="${data.quantity||1}" required /></label><label>Unidad<input class="quote-unit" readonly value="—" aria-label="Unidad de medida del producto" /></label><button class="button quote-row-action remove-quote-item" type="button">Quitar</button>`;document.querySelector('#quote-items').append(item);wireQuoteItem(item)}
async function loadProducts(){const catalog=await fetch('/api/catalog',{cache:'no-store'}).then(response=>response.json());catalogProducts=catalog.products;catalogCategories=catalog.categories;document.querySelectorAll('.quote-product').forEach(select=>{const selected=select.value;select.innerHTML=quoteOptions(selected);select.required=true});document.querySelectorAll('.quote-item').forEach(wireQuoteItem);renderCatalog()}

// Envía los productos solicitados y reinicia el formulario únicamente cuando la API acepta la cotización.
document.querySelector('#quote-form').addEventListener('submit', async (event) => {
  event.preventDefault();
  const form = new FormData(event.target); const items=[...document.querySelectorAll('.quote-item')].map(item=>({product:item.querySelector('.quote-product').value,quantity:item.querySelector('.quote-quantity').value,unit:item.querySelector('.quote-unit').value}));
  const response = await fetch('/api/quotes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({...Object.fromEntries(form),items}) });
  const data = await response.json();
  document.querySelector('#quote-message').textContent = data.message;
  if (response.ok) { trackAnalytics('producto_consultado', { productName: items.map(item=>item.product).join(', ') }); event.target.reset(); document.querySelector('#quote-items').innerHTML=''; addQuoteItem(); }
});

document.querySelector('#add-quote-item').addEventListener('click',()=>addQuoteItem());

// Controla la apertura del formulario laboral, el documento de identidad y el archivo adjunto.
const jobApplicationForm=document.querySelector('#job-application-form'),careersLayout=document.querySelector('#careers-layout'),openJobApplicationButton=document.querySelector('#open-job-application'),cancelJobApplicationButton=document.querySelector('#cancel-job-application'),jobApplicationMessage=document.querySelector('#job-application-message'),jobApplicationFileInput=document.querySelector('#job-application-cv'),jobApplicationFileName=document.querySelector('#job-application-file-name'),jobApplicationDocumentType=document.querySelector('#job-application-document-type'),jobApplicationDocumentToggle=document.querySelector('#job-application-document-toggle'),jobApplicationDocumentLabel=document.querySelector('#job-application-document-label'),jobApplicationDocumentOptions=document.querySelector('#job-application-document-options');
function resetJobApplicationFileName(){jobApplicationFileName.textContent='Ningún archivo seleccionado'}function validateJobApplicationDocument(){const input=jobApplicationForm.elements.dni,length=jobApplicationDocumentType.value==='CE'?9:8,label=jobApplicationDocumentType.value==='CE'?'Carnet de Extranjería':'DNI',value=input.value;input.setCustomValidity(value&&value.length!==length?`El ${label} debe tener exactamente ${length} dígitos.`:'');return value.length===length}function syncJobApplicationDocument(){const isCe=jobApplicationDocumentType.value==='CE',length=isCe?9:8,input=jobApplicationForm.elements.dni;jobApplicationDocumentLabel.textContent=jobApplicationDocumentType.value;jobApplicationDocumentOptions.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.documentType===jobApplicationDocumentType.value));input.minLength=length;input.maxLength=length;input.pattern=`[0-9]{${length}}`;input.placeholder=isCe?'123456789':'12345678';input.value=input.value.slice(0,length);validateJobApplicationDocument()}function closeJobApplicationDocumentOptions(){jobApplicationDocumentOptions.classList.add('hidden');jobApplicationDocumentToggle.setAttribute('aria-expanded','false')}function toggleJobApplicationForm(open){if(open){jobApplicationForm.classList.remove('hidden');requestAnimationFrame(()=>careersLayout.classList.add('is-form-open'));return}careersLayout.classList.remove('is-form-open');setTimeout(()=>{if(!careersLayout.classList.contains('is-form-open'))jobApplicationForm.classList.add('hidden')},400)}
// Valida el documento y el PDF antes de enviar la postulación y muestra la respuesta recibida.
openJobApplicationButton.addEventListener('click',()=>toggleJobApplicationForm(true));cancelJobApplicationButton.addEventListener('click',()=>{jobApplicationForm.reset();syncJobApplicationDocument();resetJobApplicationFileName();jobApplicationMessage.textContent='';closeJobApplicationDocumentOptions();toggleJobApplicationForm(false)});jobApplicationFileInput.addEventListener('change',()=>{jobApplicationFileName.textContent=jobApplicationFileInput.files[0]?.name||'Ningún archivo seleccionado'});jobApplicationDocumentToggle.addEventListener('click',()=>{const open=jobApplicationDocumentOptions.classList.toggle('hidden');jobApplicationDocumentToggle.setAttribute('aria-expanded',String(!open))});jobApplicationDocumentOptions.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{jobApplicationDocumentType.value=button.dataset.documentType;syncJobApplicationDocument();closeJobApplicationDocumentOptions()}));document.addEventListener('click',event=>{if(!event.target.closest('.career-document-field'))closeJobApplicationDocumentOptions()});jobApplicationForm.elements.dni.addEventListener('input',()=>{const input=jobApplicationForm.elements.dni;input.value=input.value.replace(/\D/g,'').slice(0,input.maxLength);validateJobApplicationDocument()});syncJobApplicationDocument();jobApplicationForm.addEventListener('submit',async event=>{event.preventDefault();if(!validateJobApplicationDocument()){jobApplicationMessage.textContent=jobApplicationForm.elements.dni.validationMessage;return}const cv=jobApplicationForm.elements.cv.files[0];if(!cv||cv.type!=='application/pdf'||!cv.name.toLowerCase().endsWith('.pdf')){jobApplicationMessage.textContent='Adjunta un CV válido en formato PDF.';return}if(cv.size>5*1024*1024){jobApplicationMessage.textContent='El CV no puede superar los 5 MB.';return}const button=jobApplicationForm.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Enviando…';try{const response=await fetch('/api/job-applications',{method:'POST',body:new FormData(jobApplicationForm)}),result=await response.json();jobApplicationMessage.textContent=response.ok?result.message:(result.message||'No se pudo enviar la postulación.');if(response.ok){jobApplicationForm.reset();syncJobApplicationDocument();resetJobApplicationFileName();button.textContent='Postulación enviada';}}catch{jobApplicationMessage.textContent='No se pudo enviar la postulación. Intenta nuevamente.'}finally{button.disabled=false;if(button.textContent==='Enviando…')button.textContent='Enviar postulación'}});

// Construye la política de privacidad desde secciones administrables y convierte líneas con marcadores en viñetas.
const privacyPolicyModal=document.querySelector('#privacy-policy-modal'),openPrivacyPolicyButton=document.querySelector('#open-privacy-policy'),closePrivacyPolicyButton=document.querySelector('#close-privacy-policy'),privacyPolicyIndex=document.querySelector('#privacy-policy-index'),privacyPolicyContent=document.querySelector('#privacy-policy-content');let privacyPolicyPreviousFocus=null;
function appendPrivacyPolicyText(container,value){let paragraphLines=[],list=null;const flushParagraph=()=>{if(!paragraphLines.length)return;const paragraph=document.createElement('p');paragraph.textContent=paragraphLines.join('\n');container.append(paragraph);paragraphLines=[]};String(value||'').replace(/\r\n?/g,'\n').split('\n').forEach(line=>{const bullet=line.match(/^\s*[-*•]\s+(.+)$/);if(bullet){flushParagraph();if(!list){list=document.createElement('ul');container.append(list)}const item=document.createElement('li');item.textContent=bullet[1];list.append(item);return}list=null;if(!line.trim()){flushParagraph();return}paragraphLines.push(line)});flushParagraph()}
function renderPrivacyPolicy(sections){privacyPolicyIndex.innerHTML='';privacyPolicyContent.innerHTML='';if(!sections.length){privacyPolicyContent.innerHTML='<p class="privacy-policy-empty">La política de privacidad estará disponible próximamente.</p>';return}sections.forEach((section,index)=>{const targetId=`privacy-policy-section-${section.id}`,indexButton=document.createElement('button');indexButton.type='button';indexButton.textContent=`${index+1}. ${section.title}`;indexButton.addEventListener('click',()=>{document.querySelector(`#${targetId}`)?.scrollIntoView({behavior:'smooth',block:'start'});privacyPolicyContent.focus({preventScroll:true})});privacyPolicyIndex.append(indexButton);const article=document.createElement('article');article.id=targetId;article.className='privacy-policy-section';const heading=document.createElement('div');heading.className='privacy-policy-section-heading';const number=document.createElement('span');number.className='privacy-policy-number';number.textContent=String(index+1);const title=document.createElement('h3');title.textContent=section.title;heading.append(number,title);article.append(heading);appendPrivacyPolicyText(article,section.content);privacyPolicyContent.append(article)})}
async function openPrivacyPolicy(){privacyPolicyPreviousFocus=document.activeElement;privacyPolicyIndex.innerHTML='';privacyPolicyContent.innerHTML='<p class="privacy-policy-empty">Cargando política de privacidad…</p>';privacyPolicyModal.classList.remove('hidden');document.body.classList.add('popup-open');closePrivacyPolicyButton.focus();try{const response=await fetch('/api/privacy-policy',{cache:'no-store'}),sections=await response.json();if(!response.ok)throw new Error(sections.message||'No se pudo cargar la política de privacidad.');renderPrivacyPolicy(sections)}catch(error){privacyPolicyContent.innerHTML='';const message=document.createElement('p');message.className='privacy-policy-empty';message.textContent=error.message||'No se pudo cargar la política de privacidad.';privacyPolicyContent.append(message)}}
function closePrivacyPolicy(){privacyPolicyModal.classList.add('hidden');document.body.classList.remove('popup-open');privacyPolicyPreviousFocus?.focus();privacyPolicyPreviousFocus=null}
openPrivacyPolicyButton.addEventListener('click',openPrivacyPolicy);closePrivacyPolicyButton.addEventListener('click',closePrivacyPolicy);privacyPolicyModal.addEventListener('click',event=>{if(event.target===privacyPolicyModal)closePrivacyPolicy()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!privacyPolicyModal.classList.contains('hidden'))closePrivacyPolicy()});

// Adapta el acceso según el rol y completa los datos de cotización del cliente autenticado.
fetch('/api/auth/me').then(async (response) => { if (!response.ok) return; const { user } = await response.json(); const trackingAccess = document.querySelector('#tracking-access'); const sessionMenu = document.querySelector('#session-menu'); const destination = user.role === 'cliente' ? '/cuenta' : '/admin'; trackingAccess.href = destination; trackingAccess.textContent = user.role === 'cliente' ? 'Ver mis pedidos' : 'Ir a administración'; sessionMenu.innerHTML = `<button id="session-access" class="session-access session-icon" aria-label="Abrir menú de usuario">👤</button><div id="session-dropdown" class="session-dropdown hidden"><a href="${destination}">${user.role === 'cliente' ? 'Mi cuenta' : 'Administración'}</a><button id="session-logout">Cerrar sesión</button></div>`; document.querySelector('#session-access').onclick = () => document.querySelector('#session-dropdown').classList.toggle('hidden'); document.querySelector('#session-logout').onclick = async () => { await fetch('/api/auth/logout', { method: 'POST' }); location.reload(); }; if (user.role === 'cliente') { const clientResponse = await fetch('/api/my/client'); if (!clientResponse.ok) return; const client = await clientResponse.json(); const quoteForm = document.querySelector('#quote-form'); quoteForm.elements.name.value = client.name || ''; quoteForm.elements.email.value = client.email || ''; quoteForm.elements.name.readOnly = true; quoteForm.elements.email.readOnly = true; document.querySelector('#quote-account-note').classList.remove('hidden'); } });

/* CARGA PROGRESIVA: primero carga el catálogo y los contactos; carga las demás secciones al acercarse a ellas. */
function loadWhenNear(selector, loader) { const section = document.querySelector(selector); if (!section || !('IntersectionObserver' in window)) return loader().catch(() => {}); const observer = new IntersectionObserver((entries) => { if (!entries[0].isIntersecting) return; observer.disconnect(); loader().catch(() => {}); }, { rootMargin: '500px 0px' }); observer.observe(section); }
Promise.all([loadAnalyticsConfiguration(), loadWhatsAppSettings(), loadAbout(), loadPromotionalPopup(), loadProducts(), loadAttentionPoints(), loadBanners()]).catch(() => {});
loadWhenNear('#socios', loadCommercialPartners);
loadWhenNear('#indicadores', loadKpis);
loadWhenNear('#historia', loadTimeline);

// Revela cada sección al entrar en pantalla y deja de observarla después de mostrarla.
const sectionObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); sectionObserver.unobserve(entry.target); } });
}, { threshold: 0.12 });
document.querySelectorAll('main > .section:not(.hero)').forEach((section) => sectionObserver.observe(section));
