/* PÁGINA PÚBLICA
 * Catálogo y filtros, carrusel de banners, socios, indicadores, línea de tiempo,
 * puntos de recojo/Google Maps, formulario de cotización, redes y WhatsApp.
 */
const productList = document.querySelector('#product-list');
const productSelect = document.querySelector('#product-select');
const kpiList = document.querySelector('#kpi-list');
let catalogProducts = [];
let catalogCategories = [];
const catalogProductsByCategory = new Map();
let catalogCategoryLoading = null;
let selectedCatalogCategoryId = null;
let whatsappNumber = '';
let timelineItems = [];
let activeTimelineItem = 0;
let bannerItems = [];
let activeBannerItem = 0;
let bannerTimer = null;
let commercialPartners = [];
let commercialPartnersTimer = null;
let attentionPoints = [];
let attentionMap = null;
let attentionInfoWindow = null;
let analyticsEnabled = false;
let analyticsSession = '';
const attentionMarkers = new Map();
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character]));

function getAnalyticsSession() { try { const key = 'costa_grande_analytics_session'; let value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID().replace(/-/g, ''); localStorage.setItem(key, value); } return value; } catch { return ''; } }
function trackAnalytics(type, details = {}) { if (!analyticsEnabled || !analyticsSession) return; fetch('/api/analytics/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, session: analyticsSession, path: location.pathname, ...details }), keepalive: true }).catch(() => {}); }
async function loadAnalyticsConfiguration() { const response = await fetch('/api/analytics/config'); const configuration = await response.json(); analyticsEnabled = Boolean(configuration.enabled); if (analyticsEnabled) { analyticsSession = getAnalyticsSession(); trackAnalytics('visita_web'); } }

function contactByWhatsApp(message) {
  if (!whatsappNumber) { alert('No hay número de WhatsApp configurado. Comunícate con la empresa por sus canales de atención.'); return; }
  window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, '_blank', 'noopener');
}

function renderSocialNetworks(settings) { const networks = [['social-facebook', settings.facebookUrl], ['social-instagram', settings.instagramUrl], ['social-linkedin', settings.linkedinUrl]]; let configured = 0; networks.forEach(([id, url]) => { const link = document.querySelector(`#${id}`); if (!link) return; const visible = Boolean(url); link.classList.toggle('hidden', !visible); if (visible) { link.href = url; configured += 1; } else link.removeAttribute('href'); }); const note = document.querySelector('#social-networks-note'); if (note) note.textContent = configured ? 'Síguenos en nuestras redes oficiales.' : 'Las cuentas oficiales se podrán enlazar cuando estén disponibles.'; }
function renderContactPhone(contactPhone) { const phone = String(contactPhone || '').trim(); const callNumber = phone.replace(/[^\d+]/g, ''); ['attention-contact-phone', 'footer-contact-phone'].forEach((id) => { const container = document.querySelector(`#${id}`); if (!container) return; const link = container.querySelector('a'); container.classList.toggle('hidden', !phone); if (phone) { link.textContent = phone; link.href = `tel:${callNumber}`; } else { link.textContent = ''; link.removeAttribute('href'); } }); }
function renderContactEmail(contactEmail) { const email = String(contactEmail || '').trim(); const container = document.querySelector('#footer-contact-email'); if (!container) return; const link = container.querySelector('a'); container.classList.toggle('hidden', !email); if (email) { link.textContent = email; link.href = `mailto:${email}`; } else { link.textContent = ''; link.removeAttribute('href'); } }
async function loadWhatsAppSettings() { const settings = await fetch('/api/company-settings').then((response) => response.json()); whatsappNumber = settings.whatsappNumber || ''; renderSocialNetworks(settings); renderContactPhone(settings.contactPhone); renderContactEmail(settings.contactEmail); }
async function loadAbout() { const settings = await fetch('/api/about').then((response) => response.json()); const description = document.querySelector('#about-description'); const image = document.querySelector('#about-image'); if (description && settings.description) description.textContent = settings.description; if (image && settings.hasImage) image.src = '/api/about/image'; }
function googleMapsUrl(point) { return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${point.address}, Perú`)}`; }
function renderAttentionPoints() { const list = document.querySelector('#attention-list'); list.innerHTML = attentionPoints.map((point) => `<article class="attention-point"><h3>${escapeHtml(point.name)}</h3><p>${escapeHtml(point.address)}</p><p class="attention-schedule">Horario de atención: ${escapeHtml(point.schedule || '7am a 6pm')}</p><div><button class="attention-focus" data-id="${point.id}" type="button">Ver en el mapa</button><a href="${googleMapsUrl(point)}" target="_blank" rel="noopener">Abrir en Google Maps ↗</a></div></article>`).join('') || '<p>No hay puntos de atención registrados.</p>'; document.querySelectorAll('.attention-focus').forEach((button) => button.addEventListener('click', () => focusAttentionPoint(Number(button.dataset.id)))); }
function loadGoogleMaps(apiKey) { if (window.google?.maps) return Promise.resolve(); return new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey)}`; script.async = true; script.onload = resolve; script.onerror = () => reject(new Error('No fue posible cargar Google Maps.')); document.head.append(script); }); }
async function initializeAttentionMap(apiKey) { const mapElement = document.querySelector('#attention-map'); const mapMessage = document.querySelector('#attention-map-message'); if (!apiKey) { mapElement.innerHTML = '<p class="map-placeholder">Configura la clave de Google Maps para ver todos los puntos marcados aquí.</p>'; mapMessage.textContent = 'Mientras tanto, puedes abrir cada dirección directamente en Google Maps.'; return; } try { await loadGoogleMaps(apiKey); attentionMap = new google.maps.Map(mapElement, { center: { lat: -6.48, lng: -76.37 }, zoom: 8, mapTypeControl: false, streetViewControl: false, fullscreenControl: true }); attentionInfoWindow = new google.maps.InfoWindow(); const bounds = new google.maps.LatLngBounds(); const mappedPoints = attentionPoints.filter((point) => point.latitude !== null && point.longitude !== null && Number.isFinite(Number(point.latitude)) && Number.isFinite(Number(point.longitude))); mappedPoints.forEach((point) => { const position = { lat: Number(point.latitude), lng: Number(point.longitude) }; const marker = new google.maps.Marker({ map: attentionMap, position, title: point.name }); marker.addListener('click', () => focusAttentionPoint(point.id)); attentionMarkers.set(point.id, { marker, position, point }); bounds.extend(position); }); if (!bounds.isEmpty()) { attentionMap.fitBounds(bounds, 48); google.maps.event.addListenerOnce(attentionMap, 'idle', () => attentionMap.setZoom(Math.min(attentionMap.getZoom(), 14))); mapMessage.textContent = 'Selecciona una ubicación para acercarte a ese punto.'; } else mapMessage.textContent = 'Aún faltan coordenadas. Un administrador puede actualizarlas desde el panel.'; } catch (error) { mapElement.innerHTML = '<p class="map-placeholder">No fue posible cargar el mapa.</p>'; mapMessage.textContent = error.message; } }
function focusAttentionPoint(id) { const point = attentionPoints.find((item) => item.id === id); const markerData = attentionMarkers.get(id); document.querySelectorAll('.attention-point').forEach((item) => item.classList.toggle('selected', Number(item.querySelector('.attention-focus')?.dataset.id) === id)); if (markerData && attentionMap) { attentionMap.panTo(markerData.position); attentionMap.setZoom(17); attentionInfoWindow.setContent(`<strong>${escapeHtml(point.name)}</strong><br>${escapeHtml(point.address)}`); attentionInfoWindow.open({ map: attentionMap, anchor: markerData.marker }); } else if (point) window.open(googleMapsUrl(point), '_blank', 'noopener'); }
async function loadAttentionPoints() { attentionPoints = await fetch('/api/attention-points').then((response) => response.json()); renderAttentionPoints(); }
async function loadAttentionMap() { const configuration = await fetch('/api/maps/config').then((response) => response.json()); await initializeAttentionMap(configuration.apiKey || ''); }
async function loadBanners() { bannerItems = await fetch('/api/banners').then((response) => response.json()); activeBannerItem = 0; clearInterval(bannerTimer); renderBanner(); if (bannerItems.length > 1) bannerTimer = setInterval(() => moveBanner(1), 15000); }
function renderBanner() { const slider = document.querySelector('#banner-slider'), numbers = document.querySelector('#banner-numbers'); const hasManyBanners = bannerItems.length > 1; if (!bannerItems.length) { slider.parentElement.classList.add('hidden'); return; } slider.parentElement.classList.remove('hidden'); const banner = bannerItems[activeBannerItem]; slider.innerHTML = `<img class="banner-slide" fetchpriority="high" decoding="async" src="/api/banners/${banner.id}/image" alt="Banner publicitario ${activeBannerItem + 1}">`; document.querySelectorAll('.banner-arrow').forEach((button) => { button.classList.toggle('hidden', !hasManyBanners); }); numbers.classList.toggle('hidden', !hasManyBanners); numbers.innerHTML = hasManyBanners ? bannerItems.map((_, index) => `<button class="banner-number ${index === activeBannerItem ? 'active' : ''}" type="button" aria-label="Ver banner ${index + 1}" aria-current="${index === activeBannerItem ? 'true' : 'false'}">${String(index + 1).padStart(2, '0')}</button>`).join('') : ''; numbers.querySelectorAll('.banner-number').forEach((button, index) => button.addEventListener('click', () => { activeBannerItem = index; renderBanner(); })); }
function moveBanner(direction) { if (bannerItems.length < 2) return; activeBannerItem = (activeBannerItem + direction + bannerItems.length) % bannerItems.length; renderBanner(); }
async function loadCommercialPartners() { commercialPartners = await fetch('/api/commercial-partners').then((response) => response.json()); const track = document.querySelector('#commercial-partners-track'); clearInterval(commercialPartnersTimer); if (!commercialPartners.length) { track.innerHTML = '<p class="partners-empty">Próximamente compartiremos a nuestros socios comerciales.</p>'; return; } const cards = commercialPartners.map((partner) => `<article class="commercial-partner"><img src="${partner.image}" alt="Logo de ${escapeHtml(partner.name)}"><span>${escapeHtml(partner.name)}</span></article>`).join(''); track.innerHTML = cards; const carousel = commercialPartners.length > 5; track.classList.toggle('is-carousel', carousel); if (carousel) commercialPartnersTimer = setInterval(() => { const maximum = track.scrollWidth - track.clientWidth; const atEnd = track.scrollLeft >= maximum - 4; track.scrollTo({ left: atEnd ? 0 : Math.min(track.scrollLeft + track.clientWidth / 2, maximum), behavior: 'smooth' }); }, 4000); }
async function loadKpis() { const kpis = await fetch('/api/kpis').then((response) => response.json()); kpiList.innerHTML = kpis.map((kpi) => `<article class="kpi-card"><span class="kpi-value">${escapeHtml(kpi.value)}</span><h3>${escapeHtml(kpi.title)}</h3><p>${escapeHtml(kpi.description || '')}</p></article>`).join(''); }
async function loadTimeline() { timelineItems = await fetch('/api/timeline').then((response) => response.json()); activeTimelineItem = 0; renderTimeline(); }
function renderTimeline() { if (!timelineItems.length) return; const item = timelineItems[activeTimelineItem]; const previous = activeTimelineItem > 0 ? timelineItems[activeTimelineItem - 1] : null; const next = activeTimelineItem < timelineItems.length - 1 ? timelineItems[activeTimelineItem + 1] : null; const image = item.image ? `<img class="timeline-image" src="${item.image}" alt="${escapeHtml(item.title)}">` : ''; document.querySelector('#timeline-slider').innerHTML = `<article class="timeline-slide"><div class="timeline-side">${previous ? `<strong>${escapeHtml(previous.year)}</strong><p>${escapeHtml(previous.title)}</p>` : ''}</div><div class="timeline-featured ${image ? 'with-image' : ''}"><div><time>${escapeHtml(item.year)}</time><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.text)}</p></div>${image}</div><div class="timeline-side">${next ? `<strong>${escapeHtml(next.year)}</strong><p>${escapeHtml(next.title)}</p>` : ''}</div></article>`; document.querySelector('#timeline-dots').innerHTML = timelineItems.map((entry, index) => `<button class="timeline-dot ${index === activeTimelineItem ? 'active' : ''}" type="button" aria-label="Ver año ${escapeHtml(entry.year)}"></button>`).join(''); document.querySelector('#timeline-previous').disabled = !previous; document.querySelector('#timeline-next').disabled = !next; document.querySelectorAll('.timeline-dot').forEach((button, index) => button.addEventListener('click', () => { activeTimelineItem = index; renderTimeline(); })); }
function moveTimeline(direction) { const target = activeTimelineItem + direction; if (target < 0 || target >= timelineItems.length) return; activeTimelineItem = target; renderTimeline(); }
document.querySelector('#timeline-previous').addEventListener('click', () => moveTimeline(-1)); document.querySelector('#timeline-next').addEventListener('click', () => moveTimeline(1)); let timelineTouchStart = 0; document.querySelector('#timeline-slider').addEventListener('touchstart', (event) => { timelineTouchStart = event.changedTouches[0].screenX; }, { passive: true }); document.querySelector('#timeline-slider').addEventListener('touchend', (event) => { const distance = event.changedTouches[0].screenX - timelineTouchStart; if (Math.abs(distance) > 40) moveTimeline(distance < 0 ? 1 : -1); }, { passive: true });
document.querySelector('#banner-previous').addEventListener('click', () => moveBanner(-1)); document.querySelector('#banner-next').addEventListener('click', () => moveBanner(1));
document.querySelector('#whatsapp-general').addEventListener('click', () => { trackAnalytics('clic_whatsapp'); contactByWhatsApp('Hola, deseo comunicarme con atención comercial.'); });

const mobileMenuToggle = document.querySelector('#mobile-menu-toggle');
const mainNavigation = document.querySelector('#main-navigation');
mobileMenuToggle.addEventListener('click', () => {
  const isOpen = mainNavigation.classList.toggle('is-open');
  mobileMenuToggle.classList.toggle('is-open', isOpen);
  mobileMenuToggle.setAttribute('aria-expanded', String(isOpen));
  mobileMenuToggle.setAttribute('aria-label', isOpen ? 'Cerrar menú' : 'Abrir menú');
});
mainNavigation.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => {
  mainNavigation.classList.remove('is-open'); mobileMenuToggle.classList.remove('is-open'); mobileMenuToggle.setAttribute('aria-expanded', 'false'); mobileMenuToggle.setAttribute('aria-label', 'Abrir menú');
}));

function productCard(product){const visual=product.image&&(product.image.startsWith('data:image/')||product.image.startsWith('/media/'))?`<img class="product-photo" loading="lazy" decoding="async" src="${product.image}" alt="${escapeHtml(product.name)}">`:`<div class="product-icon">${escapeHtml(product.image||'📦')}</div>`;return `<article class="product product-card" tabindex="0">${visual}<div class="product-name"><h3>${escapeHtml(product.name)}</h3></div><div class="product-details"><p class="category">${escapeHtml(product.parentCategory?`${product.parentCategory} / ${product.category}`:product.category)}</p><p>${escapeHtml(product.description)}</p><button class="button select-product" data-product="${escapeHtml(product.name)}">Cotizar este producto</button><button class="text-button whatsapp-product" data-product="${escapeHtml(product.name)}">Consultar por WhatsApp</button></div></article>`}
function categoryCard(category){const visual=category.hasImage?`<img class="category-photo" loading="lazy" decoding="async" src="/api/catalog/categories/${category.id}/image" alt="${escapeHtml(category.name)}">`:`<div class="category-placeholder">${escapeHtml(category.name.slice(0,1).toUpperCase())}</div>`;const total=Number(category.productCount||0);return `<button class="catalog-category-card" type="button" data-category-id="${category.id}">${visual}<span><small>${total?`${total} ${total===1?'opción':'opciones'}`:'Explorar'}</small>${escapeHtml(category.name)}<b aria-hidden="true">→</b></span></button>`}
function scrollCatalogElement(selector,direction){const element=document.querySelector(selector);if(element)element.scrollBy({left:direction*element.clientWidth*.8,behavior:'smooth'})}
function keepProductsInView(){if(window.matchMedia('(max-width:700px)').matches)requestAnimationFrame(()=>productList.scrollIntoView({behavior:'smooth',block:'start'}))}
function bindCatalogInteractions(){document.querySelectorAll('.catalog-category-card,.catalog-filter').forEach(button=>button.addEventListener('click',()=>{selectedCatalogCategoryId=button.dataset.categoryId?Number(button.dataset.categoryId):null;const category=catalogCategories.find(item=>item.id===selectedCatalogCategoryId);if(category)trackAnalytics('categoria_abierta',{categoryId:category.id,categoryName:category.name});renderCatalog();if(category)keepProductsInView()}));document.querySelector('#catalog-previous')?.addEventListener('click',()=>scrollCatalogElement('#product-list',-1));document.querySelector('#catalog-next')?.addEventListener('click',()=>scrollCatalogElement('#product-list',1));document.querySelector('#catalog-filter-previous')?.addEventListener('click',()=>scrollCatalogElement('#catalog-filter-track',-1));document.querySelector('#catalog-filter-next')?.addEventListener('click',()=>scrollCatalogElement('#catalog-filter-track',1));document.querySelectorAll('.select-product').forEach(button=>button.addEventListener('click',()=>{trackAnalytics('producto_consultado',{productName:button.dataset.product});productSelect.value=button.dataset.product;document.querySelector('#cotizacion').scrollIntoView({behavior:'smooth'})}));document.querySelectorAll('.whatsapp-product').forEach(button=>button.addEventListener('click',()=>{trackAnalytics('clic_whatsapp',{productName:button.dataset.product});contactByWhatsApp(`Hola, deseo consultar por el producto: ${button.dataset.product}.`)}))}
function renderCatalog(){const title=document.querySelector('#catalog-title'),navigation=document.querySelector('#catalog-navigation'),previous=document.querySelector('#catalog-previous'),next=document.querySelector('#catalog-next'),categories=catalogCategories,filters=[`<button class="catalog-filter ${selectedCatalogCategoryId===null?'active':''}" type="button">Todas las categorías</button>`,...categories.map(category=>`<button class="catalog-filter ${selectedCatalogCategoryId===category.id?'active':''}" type="button" data-category-id="${category.id}">${escapeHtml(category.name)}</button>`)].join(''),hasFilterCarousel=categories.length>8,hasCategoryCarousel=!selectedCatalogCategoryId&&categories.length>4;navigation.innerHTML=`<button id="catalog-filter-previous" class="catalog-filter-arrow ${hasFilterCarousel?'':'hidden'}" type="button" aria-label="Ver categorías anteriores">‹</button><div id="catalog-filter-track" class="catalog-filter-track ${hasFilterCarousel?'is-carousel':''}">${filters}</div><button id="catalog-filter-next" class="catalog-filter-arrow ${hasFilterCarousel?'':'hidden'}" type="button" aria-label="Ver más categorías">›</button>`;productList.classList.toggle('catalog-carousel',hasCategoryCarousel);productList.classList.toggle('catalog-grid',!hasCategoryCarousel);previous.classList.toggle('hidden',!hasCategoryCarousel);next.classList.toggle('hidden',!hasCategoryCarousel);if(!selectedCatalogCategoryId){title.innerHTML='Conoce nuestros <em>productos</em>';productList.innerHTML=categories.map(categoryCard).join('')||'<p>Aún no hay categorías registradas.</p>';bindCatalogInteractions();return}const category=catalogCategories.find(item=>item.id===selectedCatalogCategoryId);if(!category){selectedCatalogCategoryId=null;return renderCatalog()}title.textContent=category.name;const products=catalogProductsByCategory.get(category.id);if(!products){productList.innerHTML='<p>Cargando productos…</p>';loadCategoryProducts(category.id);return}productList.innerHTML=products.map(productCard).join('')||'<p>Esta categoría aún no tiene productos registrados.</p>';bindCatalogInteractions()}
async function loadCategoryProducts(categoryId){if(catalogProductsByCategory.has(categoryId)||catalogCategoryLoading===categoryId)return;catalogCategoryLoading=categoryId;try{const products=await fetch(`/api/catalog/categories/${categoryId}/products`).then(response=>response.json());catalogProductsByCategory.set(categoryId,products);if(selectedCatalogCategoryId===categoryId){renderCatalog();keepProductsInView()}}finally{catalogCategoryLoading=null}}
async function loadProducts(){const catalog=await fetch('/api/catalog').then(response=>response.json());catalogProducts=catalog.products;catalogCategories=catalog.categories;productSelect.innerHTML=`<option value="">Selecciona un producto</option>${catalogProducts.map(product=>`<option>${escapeHtml(product.name)}</option>`).join('')}`;renderCatalog()}

document.querySelector('#quote-form').addEventListener('submit', async (event) => {
  event.preventDefault();
  const form = new FormData(event.target);
  const response = await fetch('/api/quotes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) });
  const data = await response.json();
  document.querySelector('#quote-message').textContent = data.message;
  if (response.ok) { trackAnalytics('producto_consultado', { productName: form.get('product') }); event.target.reset(); }
});

const jobApplicationForm=document.querySelector('#job-application-form'),careerInvitation=document.querySelector('#career-invitation'),openJobApplicationButton=document.querySelector('#open-job-application'),cancelJobApplicationButton=document.querySelector('#cancel-job-application'),jobApplicationMessage=document.querySelector('#job-application-message');
function toggleJobApplicationForm(open){jobApplicationForm.classList.toggle('hidden',!open);careerInvitation.classList.toggle('hidden',open);if(open)jobApplicationForm.scrollIntoView({behavior:'smooth',block:'center'});}
openJobApplicationButton.addEventListener('click',()=>toggleJobApplicationForm(true));cancelJobApplicationButton.addEventListener('click',()=>{jobApplicationForm.reset();jobApplicationMessage.textContent='';toggleJobApplicationForm(false)});jobApplicationForm.elements.dni.addEventListener('input',()=>{jobApplicationForm.elements.dni.value=jobApplicationForm.elements.dni.value.replace(/\D/g,'')});jobApplicationForm.addEventListener('submit',async event=>{event.preventDefault();const cv=jobApplicationForm.elements.cv.files[0];if(!cv||cv.type!=='application/pdf'||!cv.name.toLowerCase().endsWith('.pdf')){jobApplicationMessage.textContent='Adjunta un CV válido en formato PDF.';return}if(cv.size>5*1024*1024){jobApplicationMessage.textContent='El CV no puede superar los 5 MB.';return}const button=jobApplicationForm.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Enviando…';try{const response=await fetch('/api/job-applications',{method:'POST',body:new FormData(jobApplicationForm)}),result=await response.json();jobApplicationMessage.textContent=response.ok?result.message:(result.message||'No se pudo enviar la postulación.');if(response.ok){jobApplicationForm.reset();button.textContent='Postulación enviada';}}catch{jobApplicationMessage.textContent='No se pudo enviar la postulación. Intenta nuevamente.'}finally{button.disabled=false;if(button.textContent==='Enviando…')button.textContent='Enviar postulación'}});

fetch('/api/auth/me').then(async (response) => { if (!response.ok) return; const { user } = await response.json(); const trackingAccess = document.querySelector('#tracking-access'); const sessionMenu = document.querySelector('#session-menu'); const destination = user.role === 'cliente' ? '/cuenta' : '/admin'; trackingAccess.href = destination; trackingAccess.textContent = user.role === 'cliente' ? 'Ver mis pedidos' : 'Ir a administración'; sessionMenu.innerHTML = `<button id="session-access" class="session-access session-icon" aria-label="Abrir menú de usuario">👤</button><div id="session-dropdown" class="session-dropdown hidden"><a href="${destination}">${user.role === 'cliente' ? 'Mi cuenta' : 'Administración'}</a><button id="session-logout">Cerrar sesión</button></div>`; document.querySelector('#session-access').onclick = () => document.querySelector('#session-dropdown').classList.toggle('hidden'); document.querySelector('#session-logout').onclick = async () => { await fetch('/api/auth/logout', { method: 'POST' }); location.reload(); }; if (user.role === 'cliente') { const clientResponse = await fetch('/api/my/client'); if (!clientResponse.ok) return; const client = await clientResponse.json(); const quoteForm = document.querySelector('#quote-form'); quoteForm.elements.name.value = client.name || ''; quoteForm.elements.email.value = client.email || ''; quoteForm.elements.name.readOnly = true; quoteForm.elements.email.readOnly = true; document.querySelector('#quote-account-note').classList.remove('hidden'); } });

/* CARGA PROGRESIVA: el catálogo y los contactos se priorizan; las secciones lejanas se descargan al aproximarse. */
function loadWhenNear(selector, loader) { const section = document.querySelector(selector); if (!section || !('IntersectionObserver' in window)) return loader().catch(() => {}); const observer = new IntersectionObserver((entries) => { if (!entries[0].isIntersecting) return; observer.disconnect(); loader().catch(() => {}); }, { rootMargin: '500px 0px' }); observer.observe(section); }
Promise.all([loadAnalyticsConfiguration(), loadWhatsAppSettings(), loadAbout(), loadProducts(), loadAttentionPoints(), loadBanners()]).catch(() => {});
loadWhenNear('#socios', loadCommercialPartners);
loadWhenNear('#indicadores', loadKpis);
loadWhenNear('#historia', loadTimeline);
loadWhenNear('#contacto', loadAttentionMap);

const sectionObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); sectionObserver.unobserve(entry.target); } });
}, { threshold: 0.12 });
document.querySelectorAll('main > .section:not(.hero)').forEach((section) => sectionObserver.observe(section));
