let products=[],quotes=[],quoteBeingEdited=null,departments=[],provinces=[];
const clientForm=document.querySelector('#client-form'),field=name=>clientForm.elements.namedItem(name),documentTypeField=document.querySelector('#client-document-type'),documentNumberField=document.querySelector('#client-document-number'),departmentField=document.querySelector('#client-department'),provinceField=document.querySelector('#client-province');
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function productOptions(selected=''){return '<option value="">Selecciona un producto</option>'+products.map(p=>'<option '+(p.name===selected?'selected':'')+'>'+escapeHtml(p.name)+'</option>').join('')}
function setDocumentRules(){const length=documentTypeField.value==='RUC'?11:8;documentNumberField.maxLength=length;documentNumberField.minLength=length;documentNumberField.pattern='[0-9]{'+length+'}';documentNumberField.placeholder=documentTypeField.value?length+' dígitos':'Primero selecciona DNI o RUC'}
function fillDepartments(selected=''){departmentField.innerHTML='<option value="">Selecciona un departamento</option>'+departments.map(item=>'<option value="'+escapeHtml(item.departamento)+'">'+escapeHtml(item.departamento)+'</option>').join('');departmentField.value=selected}
function fillProvinces(department='',selected=''){const item=departments.find(entry=>entry.departamento===department),choices=item?provinces.filter(entry=>String(entry.departamento_id)===String(item.id)):[];provinceField.disabled=!item;provinceField.innerHTML='<option value="">'+(item?'Selecciona una provincia':'Primero selecciona un departamento')+'</option>'+choices.map(entry=>'<option value="'+escapeHtml(entry.provincia)+'">'+escapeHtml(entry.provincia)+'</option>').join('');provinceField.value=selected}
async function loadLocations(){try{const results=await Promise.all([fetch('https://raw.githubusercontent.com/RitchieRD/ubigeos-peru-data/main/json/1_ubigeo_departamentos.json').then(r=>r.json()),fetch('https://raw.githubusercontent.com/RitchieRD/ubigeos-peru-data/main/json/2_ubigeo_provincias.json').then(r=>r.json())]);departments=results[0].ubigeo_departamentos||[];provinces=results[1].ubigeo_provincias||[];const department=departmentField.value,province=provinceField.value;fillDepartments(department);fillProvinces(department,province)}catch{departmentField.innerHTML='<option value="">No fue posible cargar la lista</option>';document.querySelector('#client-message').textContent='No se pudo cargar la lista de departamentos y provincias. Revisa tu conexión a internet y vuelve a abrir la página.'}}
function setClientEditing(editing){clientForm.querySelectorAll('input,textarea,select').forEach(item=>item.disabled=!editing);clientForm.querySelector('.button').style.display=editing?'inline-block':'none';document.querySelector('#edit-client-data').style.display=editing?'none':'inline-block';document.querySelector('#cancel-client-edit').style.display=editing?'inline-block':'none'}
function renderQuotes(){document.querySelector('#quotes').innerHTML=quotes.length?quotes.map(q=>'<div class="row"><strong>'+escapeHtml(q.code)+' · '+escapeHtml(q.product)+'</strong><br><small>'+escapeHtml(q.status)+(q.message?' · '+escapeHtml(q.message):'')+'</small>'+(q.status==='Pendiente'?'<br><button class="button edit-quote" data-id="'+q.id+'">Editar</button>':'')+'</div>').join(''):'<p>Aún no tienes cotizaciones.</p>';document.querySelectorAll('.edit-quote').forEach(button=>button.onclick=()=>startQuoteEdit(quotes.find(q=>q.id===Number(button.dataset.id))))}
function startQuoteEdit(quote){quoteBeingEdited=quote;document.querySelector('#edit-quote-product').innerHTML=productOptions(quote.product);document.querySelector('#quote-edit-form').message.value=quote.message||'';document.querySelector('#quote-edit-form').classList.remove('hidden')}
function resetQuoteEditor(){quoteBeingEdited=null;document.querySelector('#quote-edit-form').reset();document.querySelector('#quote-edit-form').classList.add('hidden')}
async function load(){const me=await fetch('/api/auth/me');if(!me.ok)return location.href='/login';const user=(await me.json()).user;if(user.role!=='cliente')return location.href='/admin';products=await fetch('/api/products').then(r=>r.json());document.querySelector('#new-quote-product').innerHTML=productOptions();const client=await fetch('/api/my/client').then(r=>r.json());document.querySelector('#customer-name').textContent=client.name;Object.entries({name:client.name,email:client.email,company:client.company||'',phone:client.phone||'',documentType:client.documentType||'',documentNumber:client.documentNumber||'',department:client.department||'',province:client.province||'',district:client.district||'',address:client.address||''}).forEach(([key,value])=>field(key).value=value);setDocumentRules();fillProvinces(client.department||'',client.province||'');setClientEditing(false);quotes=await fetch('/api/my/quotes').then(r=>r.json());renderQuotes();const orders=await fetch('/api/my/orders').then(r=>r.json());document.querySelector('#orders').innerHTML=orders.length?orders.map(order=>'<div class="row"><strong>'+escapeHtml(order.code)+' · '+escapeHtml(order.status)+'</strong><br><small>'+escapeHtml(order.product)+' · '+escapeHtml(order.quantity)+' '+escapeHtml(order.unit)+' · Entrega estimada: '+escapeHtml(order.estimatedDeliveryDate)+'</small></div>').join(''):'<p>Aún no tienes pedidos.</p>'}
const editClientButton=document.createElement('button');editClientButton.id='edit-client-data';editClientButton.type='button';editClientButton.className='button';editClientButton.textContent='Editar mis datos';clientForm.before(editClientButton);const cancelClientButton=document.createElement('button');cancelClientButton.id='cancel-client-edit';cancelClientButton.type='button';cancelClientButton.className='logout';cancelClientButton.textContent='Cancelar';clientForm.querySelector('.button').after(cancelClientButton);editClientButton.onclick=()=>setClientEditing(true);cancelClientButton.onclick=()=>load();
documentTypeField.addEventListener('change',setDocumentRules);departmentField.addEventListener('change',()=>fillProvinces(departmentField.value));documentNumberField.addEventListener('input',()=>documentNumberField.value=documentNumberField.value.replace(/\D/g,''));field('phone').addEventListener('input',()=>field('phone').value=field('phone').value.replace(/\D/g,''));
clientForm.addEventListener('submit',async event=>{event.preventDefault();const response=await fetch('/api/my/client',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))}),result=await response.json();document.querySelector('#client-message').textContent=response.ok?'Datos actualizados.':(result.message||'No se pudieron actualizar.');if(response.ok)load()});
document.querySelector('#new-quote-form').addEventListener('submit',async event=>{event.preventDefault();const response=await fetch('/api/my/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});document.querySelector('#new-quote-message').textContent=response.ok?'Cotización enviada.':'No se pudo enviar.';if(response.ok){event.target.reset();load()}});
document.querySelector('#quote-edit-form').addEventListener('submit',async event=>{event.preventDefault();if(!quoteBeingEdited)return;const response=await fetch('/api/my/quotes/'+quoteBeingEdited.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});document.querySelector('#quote-edit-message').textContent=response.ok?'Cotización actualizada.':'No se pudo actualizar.';if(response.ok){resetQuoteEditor();load()}});
document.querySelector('#cancel-quote-edit').onclick=resetQuoteEditor;document.querySelector('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
document.querySelector('#password-change-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,password=form.password.value,confirmation=form.confirmation.value,message=document.querySelector('#password-change-message');if(password!==confirmation){message.textContent='Las contraseñas no coinciden.';return}const response=await fetch('/api/my/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}),result=await response.json();message.textContent=response.ok?'Contraseña actualizada.':(result.message||'No se pudo actualizar la contraseña.');if(response.ok){form.reset();document.querySelector('#password-change-section').classList.add('hidden')}});
loadLocations().then(async()=>{await load();const me=await fetch('/api/auth/me');if(me.ok){const user=(await me.json()).user;document.querySelector('#password-change-section').classList.toggle('hidden',!user.mustChangePassword)}});
