let quotes=[],orderOptions={products:[],units:[]},selectedQuote=null;
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const itemText=items=>(items||[]).map(item=>`${escapeHtml(item.product)} · ${escapeHtml(item.quantity)} ${escapeHtml(item.unit)} · S/. ${Number(item.price||0).toFixed(2)} · Total: S/. ${(Number(item.quantity||0)*Number(item.price||0)).toFixed(2)}`).join('<br>');
async function loadQuotes(){quotes=await fetch('/api/quotes').then(r=>r.json());document.querySelector('#quotes').innerHTML=quotes.length?quotes.map(quote=>`<div class="row"><div><strong>${escapeHtml(quote.code)} · ${escapeHtml(quote.name)}</strong><small>${itemText(quote.items)}${quote.message?`<br>${escapeHtml(quote.message)}`:''}${quote.orderCode?`<br>Pedido asociado: ${escapeHtml(quote.orderCode)}`:''}</small></div>${quote.orderCode?'<strong>Pedido creado</strong>':`<button class="button prepare-order" data-id="${quote.id}">Preparar pedido</button>`}</div>`).join(''):'<p>Aún no hay cotizaciones.</p>';document.querySelectorAll('.prepare-order').forEach(button=>button.onclick=()=>openOrder(quotes.find(quote=>quote.id===Number(button.dataset.id))))}
async function loadOrders(){const orders=await fetch('/api/orders').then(r=>r.json());document.querySelector('#orders').innerHTML=orders.length?orders.map(order=>`<div class="row"><div><strong>${escapeHtml(order.code)} · ${escapeHtml(order.customer)}</strong><small>${itemText(order.items)}<br>Entrega estimada: ${escapeHtml(order.estimatedDeliveryDate)}</small></div><label class="order-status-field">Estado del pedido<select class="sales-order-status" data-code="${escapeHtml(order.code)}"><option ${order.status==='Pedido en curso'?'selected':''}>Pedido en curso</option><option ${order.status==='Pedido en camino'?'selected':''}>Pedido en camino</option><option ${order.status==='Pedido entregado'?'selected':''}>Pedido entregado</option><option ${order.status==='Cancelado'?'selected':''}>Cancelado</option></select></label></div>`).join(''):'<p>Aún no hay pedidos.</p>';document.querySelectorAll('.sales-order-status').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;const response=await fetch(`/api/orders/${select.dataset.code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});if(!response.ok){const result=await response.json();alert(result.message||'No se pudo actualizar el estado.')}await loadOrders()}))}
function productOptions(value=''){return `<option value="">Selecciona un producto</option>${orderOptions.products.map(item=>`<option ${item.name===value?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}`}function unitOptions(value=''){return orderOptions.units.map(item=>`<option value="${escapeHtml(item.abbreviation)}" ${item.abbreviation===value?'selected':''}>${escapeHtml(item.name)} (${escapeHtml(item.abbreviation)})</option>`).join('')}
function addOrderItem(item={}){const row=document.createElement('div');row.className='line-item';row.innerHTML=`<label>Producto<select class="item-product" required>${productOptions(item.product)}</select></label><label>Cantidad<input class="item-quantity" type="number" min="0.01" step="0.01" value="${item.quantity||1}" required></label><label>Precio unitario<input class="item-price" type="number" min="0" step="0.01" value="${item.price??''}" required></label><label>Unidad<select class="item-unit" required>${unitOptions(item.unit)}</select></label><button type="button" class="text-button remove-order-item">Quitar</button>`;row.querySelector('.remove-order-item').onclick=()=>{if(document.querySelectorAll('.line-item').length===1)return;row.remove()};document.querySelector('#order-items').append(row)}
async function loadOrderOptions(){orderOptions=await fetch('/api/order-options').then(r=>r.json())}
function openOrder(quote){selectedQuote=quote;document.querySelector('#order-items').innerHTML='';(quote.items||[]).forEach(addOrderItem);if(!quote.items?.length)addOrderItem();document.querySelector('#quote-reference').textContent=`Cotización seleccionada: ${quote.code} · ${quote.name}`;document.querySelector('#order-message').textContent='';document.querySelector('#order-form-section').classList.remove('hidden');document.querySelector('#order-form-section').scrollIntoView({behavior:'smooth',block:'center'})}
function closeOrder(){selectedQuote=null;document.querySelector('#order-form-section').classList.add('hidden')}
document.querySelector('#add-order-item').onclick=()=>addOrderItem();document.querySelector('#cancel-order').onclick=closeOrder;
document.querySelector('#order-form').addEventListener('submit',async event=>{event.preventDefault();if(!selectedQuote)return;const form=new FormData(event.target),items=[...document.querySelectorAll('.line-item')].map(row=>({product:row.querySelector('.item-product').value,quantity:row.querySelector('.item-quantity').value,price:row.querySelector('.item-price').value,unit:row.querySelector('.item-unit').value}));const response=await fetch(`/api/quotes/${selectedQuote.id}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({estimatedDeliveryDate:form.get('estimatedDeliveryDate'),items})}),result=await response.json();document.querySelector('#order-message').textContent=response.ok?`Pedido ${result.order.code} creado.`:result.message;if(response.ok){closeOrder();loadQuotes();loadOrders()}});
document.querySelector('#enable-password-change').onclick=()=>document.querySelector('#password-change-form').classList.remove('hidden');document.querySelector('#cancel-password-change').onclick=()=>document.querySelector('#password-change-form').classList.add('hidden');document.querySelector('#password-change-form').addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));const message=document.querySelector('#password-message');if(data.password!==data.confirmation){message.textContent='Las contraseñas no coinciden.';return}const response=await fetch('/api/auth/password',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json();message.textContent=result.message||'Contraseña actualizada.';if(response.ok)event.target.reset()});document.querySelector('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
(async()=>{const response=await fetch('/api/auth/me');if(!response.ok)return location.href='/login';const user=(await response.json()).user;if(user.role!=='ventas')return location.href=user.role==='administracion'?'/admin':'/cuenta';if(user.mustChangePassword)document.querySelector('#password-change-note').textContent='Mantén tu cuenta protegida actualizando tu contraseña cuando lo necesites.';await loadOrderOptions();loadQuotes();loadOrders()})();
