// Conserva las cotizaciones, opciones de pedido y selección activa del usuario de ventas.
let quotes=[],orderOptions={products:[],units:[]},selectedQuote=null,editorTarget=null;
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=value=>`S/. ${Number(value||0).toFixed(2)}`,itemText=items=>(items||[]).map(item=>`${escapeHtml(item.product)} · ${escapeHtml(item.quantity)} ${escapeHtml(item.unit)} · ${money(item.price)} · Total: ${money(Number(item.quantity)*Number(item.price))}`).join('<br>');
const trash='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M10 11v6m4-6v6M9 7l1-2h4l1 2m-9 0 1 13h10l1-13" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
// Muestra las cotizaciones y permite editar sus productos o preparar un pedido.
async function loadQuotes(){quotes=await fetch('/api/quotes',{cache:'no-store'}).then(r=>r.json());const container=document.querySelector('#quotes');CostaGrandeDocumentTable.render(container,quotes,{detailLabel:'Cotización seleccionada',emptyMessage:'Aún no hay cotizaciones.',actions:quote=>`<button class="text-button edit-sales-quote" type="button">Editar productos</button>${quote.orderCode?'<span class="document-action-note">Pedido creado</span>':'<button class="button prepare-order" type="button">Preparar pedido</button>'}`,afterRender:(target,quote)=>{target.querySelector('.edit-sales-quote')?.addEventListener('click',()=>openEditor('quote',quote));target.querySelector('.prepare-order')?.addEventListener('click',()=>openOrder(quote))}})}
// Muestra los pedidos y permite modificar sus productos o su estado.
async function loadOrders(){const orders=await fetch('/api/orders',{cache:'no-store'}).then(r=>r.json());const container=document.querySelector('#orders');CostaGrandeDocumentTable.render(container,orders,{detailLabel:'Pedido seleccionado',emptyMessage:'Aún no hay pedidos.',actions:order=>`<button class="text-button edit-sales-order" type="button">Editar pedido</button><label>Estado del pedido<select class="sales-order-status"><option ${order.status==='Pedido en curso'?'selected':''}>Pedido en curso</option><option ${order.status==='Pedido en camino'?'selected':''}>Pedido en camino</option><option ${order.status==='Pedido entregado'?'selected':''}>Pedido entregado</option><option ${order.status==='Cancelado'?'selected':''}>Cancelado</option></select></label>`,afterRender:(target,order)=>{target.querySelector('.edit-sales-order')?.addEventListener('click',()=>openEditor('order',order));target.querySelector('.sales-order-status')?.addEventListener('change',async event=>{const select=event.currentTarget;select.disabled=true;const response=await fetch(`/api/orders/${encodeURIComponent(order.code)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});if(!response.ok){const result=await response.json();alert(result.message||'No se pudo actualizar el estado.')}await loadOrders()})}})}
function productOptions(value=''){return `<option value="">Selecciona un producto</option>${orderOptions.products.map(item=>`<option ${item.name===value?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}`}function unitOptions(value=''){return orderOptions.units.map(item=>`<option value="${escapeHtml(item.abbreviation)}" ${item.abbreviation===value?'selected':''}>${escapeHtml(item.name)} (${escapeHtml(item.abbreviation)})</option>`).join('')}
// Agrega una línea de producto al pedido y conserva al menos una línea.
function addOrderItem(item={}){const row=document.createElement('div');row.className='line-item';row.innerHTML=`<label>Producto<select class="item-product" required>${productOptions(item.product)}</select></label><label>Cantidad<input class="item-quantity" type="number" min="0.01" step="0.01" value="${item.quantity||1}" required></label><label>Precio unitario<input class="item-price" type="number" min="0" step="0.01" value="${item.price??''}" required></label><label>Unidad<select class="item-unit" required>${unitOptions(item.unit)}</select></label><button type="button" class="order-remove-item remove-order-item" aria-label="Quitar producto">${trash}</button>`;row.querySelector('.remove-order-item').onclick=()=>{if(document.querySelectorAll('#order-items .line-item').length>1)row.remove()};document.querySelector('#order-items').append(row)}
async function loadOrderOptions(){orderOptions=await fetch('/api/order-options').then(r=>r.json())}
// Prepara el formulario de pedido con los productos de la cotización elegida.
function openOrder(quote){selectedQuote=quote;document.querySelector('#order-items').innerHTML='';(quote.items||[]).forEach(addOrderItem);if(!quote.items?.length)addOrderItem();document.querySelector('#quote-reference').textContent=`Cotización seleccionada: ${quote.code} · ${quote.name}`;document.querySelector('#order-message').textContent='';document.querySelector('#order-form-section').classList.remove('hidden');document.querySelector('#order-form-section').scrollIntoView({behavior:'smooth',block:'center'})}function closeOrder(){selectedQuote=null;document.querySelector('#order-form-section').classList.add('hidden')}
const editor=document.querySelector('#sales-editor'),editorItems=document.querySelector('#sales-editor-items'),editorTotal=document.querySelector('#sales-editor-total'),editorMessage=document.querySelector('#sales-editor-message'),editorMessageField=document.querySelector('#sales-editor-message-field'),editorFeedback=document.querySelector('#sales-editor-feedback');
// Recalcula el total de cada producto y del documento completo.
function refreshEditor(){let total=0;editorItems.querySelectorAll('.line-item').forEach(row=>{const value=(Number(row.querySelector('.editor-qty').value)||0)*(Number(row.querySelector('.editor-price').value)||0);row.querySelector('.editor-total').value=money(value);total+=value});editorTotal.textContent=money(total)}function addEditorItem(item={}){const row=document.createElement('div');row.className='line-item';row.innerHTML=`<label>Producto<select class="editor-product" required>${productOptions(item.product)}</select></label><label>Cantidad<input class="editor-qty" type="number" min="0.01" step="0.01" value="${item.quantity||1}" required></label><label>Precio unitario<input class="editor-price" type="number" min="0" step="0.01" value="${item.price??''}" required></label><label>Unidad<select class="editor-unit" required>${unitOptions(item.unit)}</select></label><label>Total por fila<input class="editor-total" readonly></label><button type="button" class="sales-editor-remove" aria-label="Quitar producto">${trash}</button>`;row.querySelector('.sales-editor-remove').onclick=()=>{if(editorItems.querySelectorAll('.line-item').length>1){row.remove();refreshEditor()}};row.querySelector('.editor-qty').oninput=refreshEditor;row.querySelector('.editor-price').oninput=refreshEditor;editorItems.append(row);refreshEditor()}
// Abre la edición de productos para una cotización o un pedido.
function openEditor(type,item){editorTarget={type,item};editorItems.innerHTML='';(item.items||[]).forEach(addEditorItem);if(!item.items?.length)addEditorItem();const quote=type==='quote';document.querySelector('#sales-editor-title').textContent=quote?`Editar productos · ${item.code}`:`Editar pedido · ${item.code}`;document.querySelector('#sales-editor-description').textContent=quote?'Agrega, modifica o quita productos de la cotización.':'Agrega, modifica o quita productos del pedido.';editorMessageField.classList.toggle('hidden',!quote);editorMessage.value=quote?(item.message||''):'';editorFeedback.textContent='';editor.classList.remove('hidden');document.body.classList.add('popup-open');document.querySelector('#sales-editor-close').focus()}function closeEditor(){editorTarget=null;editor.classList.add('hidden');document.body.classList.remove('popup-open')}
// Guarda los cambios hechos en los productos desde el cuadro de edición.
document.querySelector('#sales-editor-add').onclick=()=>addEditorItem();document.querySelector('#sales-editor-close').onclick=closeEditor;document.querySelector('#sales-editor-cancel').onclick=closeEditor;editor.addEventListener('click',event=>{if(event.target===editor)closeEditor()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!editor.classList.contains('hidden'))closeEditor()});document.querySelector('#sales-editor-form').addEventListener('submit',async event=>{event.preventDefault();if(!editorTarget)return;const items=[...editorItems.querySelectorAll('.line-item')].map(row=>({product:row.querySelector('.editor-product').value,quantity:row.querySelector('.editor-qty').value,price:row.querySelector('.editor-price').value,unit:row.querySelector('.editor-unit').value})),{type,item}=editorTarget,url=type==='quote'?`/api/quotes/${item.id}`:`/api/orders/${encodeURIComponent(item.code)}/items`,body=type==='quote'?{items,message:editorMessage.value}:{items},response=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok){editorFeedback.textContent=result.message||'No se pudieron guardar los cambios.';return}closeEditor();if(type==='quote')loadQuotes();else loadOrders()});
// Crea el pedido con sus productos y la fecha estimada de entrega.
document.querySelector('#add-order-item').onclick=()=>addOrderItem();document.querySelector('#cancel-order').onclick=closeOrder;document.querySelector('#order-form').addEventListener('submit',async event=>{event.preventDefault();if(!selectedQuote)return;const form=new FormData(event.target),items=[...document.querySelectorAll('#order-items .line-item')].map(row=>({product:row.querySelector('.item-product').value,quantity:row.querySelector('.item-quantity').value,price:row.querySelector('.item-price').value,unit:row.querySelector('.item-unit').value}));const response=await fetch(`/api/quotes/${selectedQuote.id}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({estimatedDeliveryDate:form.get('estimatedDeliveryDate'),items})}),result=await response.json();document.querySelector('#order-message').textContent=response.ok?`Pedido ${result.order.code} creado.`:result.message;if(response.ok){closeOrder();loadQuotes();loadOrders()}});
// Permite cambiar la contraseña y cerrar la sesión del usuario de ventas.
const passwordChangeForm=document.querySelector('#password-change-form'),enablePasswordChange=document.querySelector('#enable-password-change'),cancelPasswordChange=document.querySelector('#cancel-password-change');let passwordChangeRequired=false;
enablePasswordChange.onclick=()=>passwordChangeForm.classList.remove('hidden');cancelPasswordChange.onclick=()=>{if(!passwordChangeRequired)passwordChangeForm.classList.add('hidden')};passwordChangeForm.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target)),message=document.querySelector('#password-message');if(data.password!==data.confirmation){message.textContent='Las contraseñas no coinciden.';return}const response=await fetch('/api/my/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:data.password})}),result=await response.json();message.textContent=result.message||'Contraseña actualizada.';if(response.ok)location.reload()});document.querySelector('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
// Comprueba el rol antes de cargar las cotizaciones y pedidos del panel de ventas.
(async()=>{const response=await fetch('/api/auth/me');if(!response.ok)return location.href='/login';const user=(await response.json()).user;if(user.role!=='ventas')return location.href=user.role==='administracion'?'/admin':'/cuenta';passwordChangeRequired=user.mustChangePassword;if(passwordChangeRequired){document.querySelector('#password-change-note').textContent='Ingresaste con una contraseña temporal. Crea ahora tu contraseña secreta para continuar.';passwordChangeForm.classList.remove('hidden');enablePasswordChange.classList.add('hidden');cancelPasswordChange.classList.add('hidden');document.querySelector('.section-index').classList.add('hidden');document.querySelector('#sales-quotes').classList.add('hidden');document.querySelector('#sales-orders').classList.add('hidden');passwordChangeForm.elements.password.focus();return}await loadOrderOptions();loadQuotes();loadOrders()})();
