/* PANEL DE VENTAS: listado de cotizaciones, creación de pedidos, estados y contraseña. */
let quotes=[],selectedQuote=null,orderOptions={products:[],units:[]};
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function loadQuotes(){quotes=await fetch('/api/quotes').then(r=>r.json());document.querySelector('#quotes').innerHTML=quotes.length?quotes.map(quote=>'<div class="row"><div><strong>'+escapeHtml(quote.code)+' · '+escapeHtml(quote.name)+' · '+escapeHtml(quote.product)+'</strong><small>'+escapeHtml(quote.email)+(quote.message?' · '+escapeHtml(quote.message):'')+(quote.orderCode?' · Pedido asociado: '+escapeHtml(quote.orderCode):'')+'</small></div>'+(quote.orderCode?'<strong>Pedido creado</strong>':'<button class="button prepare-order" data-id="'+quote.id+'">Preparar pedido</button>')+'</div>').join(''):'<p>Aún no hay cotizaciones.</p>';document.querySelectorAll('.prepare-order').forEach(button=>button.onclick=()=>openOrder(quotes.find(quote=>quote.id===Number(button.dataset.id))))}
async function loadOrders(){const orders=await fetch('/api/orders').then(r=>r.json());document.querySelector('#orders').innerHTML=orders.length?orders.map(order=>'<div class="row"><div><strong>'+escapeHtml(order.code)+' · '+escapeHtml(order.customer)+'</strong><small>'+escapeHtml(order.product)+' · '+escapeHtml(order.quantity)+' '+escapeHtml(order.unit)+' · Entrega estimada: '+escapeHtml(order.estimatedDeliveryDate)+'</small></div><label class="order-status-field">Estado del pedido<select class="sales-order-status" data-code="'+escapeHtml(order.code)+'"><option '+(order.status==='Pedido en curso'?'selected':'')+'>Pedido en curso</option><option '+(order.status==='Pedido en camino'?'selected':'')+'>Pedido en camino</option><option '+(order.status==='Pedido entregado'?'selected':'')+'>Pedido entregado</option><option '+(order.status==='Cancelado'?'selected':'')+'>Cancelado</option></select></label></div>').join(''):'<p>Aún no hay pedidos.</p>';document.querySelectorAll('.sales-order-status').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;const response=await fetch(`/api/orders/${select.dataset.code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})});if(!response.ok){const result=await response.json();alert(result.message||'No se pudo actualizar el estado.')}await loadOrders()}))}
async function loadOrderOptions(){orderOptions=await fetch('/api/order-options').then(r=>r.json());fillOrderOptions()}
function fillOrderOptions(product=''){const form=document.querySelector('#order-form');form.product.innerHTML=orderOptions.products.map(item=>'<option value="'+escapeHtml(item.name)+'">'+escapeHtml(item.name)+'</option>').join('');form.unit.innerHTML=orderOptions.units.map(item=>'<option value="'+escapeHtml(item.abbreviation)+'">'+escapeHtml(item.name)+' ('+escapeHtml(item.abbreviation)+')</option>').join('');form.product.value=product}
function updateOrderTotal(){const form=document.querySelector('#order-form');form.total.value=((Number(form.quantity.value)||0)*(Number(form.price.value)||0)).toFixed(2)}
function openOrder(quote){selectedQuote=quote;const form=document.querySelector('#order-form');form.reset();fillOrderOptions(quote.product);updateOrderTotal();document.querySelector('#quote-reference').textContent='Cotización seleccionada: '+quote.code+' · '+quote.name;document.querySelector('#order-message').textContent='';document.querySelector('#order-form-section').classList.remove('hidden');document.querySelector('#order-form-section').scrollIntoView({behavior:'smooth',block:'center'})}
function closeOrder(){selectedQuote=null;document.querySelector('#order-form-section').classList.add('hidden')}
document.querySelector('#order-form').addEventListener('submit',async event=>{event.preventDefault();if(!selectedQuote)return;const response=await fetch('/api/quotes/'+selectedQuote.id+'/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))}),result=await response.json();document.querySelector('#order-message').textContent=response.ok?'Pedido '+result.order.code+' creado.':result.message;if(response.ok){closeOrder();loadQuotes();loadOrders()}});
document.querySelector('#order-form').elements.quantity.addEventListener('input',updateOrderTotal);document.querySelector('#order-form').elements.price.addEventListener('input',updateOrderTotal);
document.querySelector('#cancel-order').onclick=closeOrder;
const passwordChangeSection=document.querySelector('#password-change-section'),passwordChangeForm=document.querySelector('#password-change-form'),enablePasswordChangeButton=document.querySelector('#enable-password-change');function setPasswordChangeEditing(editing){passwordChangeForm.classList.toggle('hidden',!editing);enablePasswordChangeButton.classList.toggle('hidden',editing);if(editing)passwordChangeForm.elements.password.focus()}enablePasswordChangeButton.onclick=()=>setPasswordChangeEditing(true);document.querySelector('#cancel-password-change').onclick=()=>{passwordChangeForm.reset();document.querySelector('#password-message').textContent='';setPasswordChangeEditing(false)};passwordChangeForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,message=document.querySelector('#password-message');if(form.password.value!==form.confirmation.value){message.textContent='Las contraseñas no coinciden.';return}const response=await fetch('/api/my/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:form.password.value})}),result=await response.json();message.textContent=response.ok?'Contraseña actualizada.':(result.message||'No se pudo actualizar.');if(response.ok){form.reset();setPasswordChangeEditing(false)}});
document.querySelector('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
// INICIO DE VENTAS. Texto editable de aviso para cuentas con contraseña temporal: 'Mantén tu cuenta protegida actualizando tu contraseña cuando lo necesites.'
(async()=>{const response=await fetch('/api/auth/me');if(!response.ok)return location.href='/login';const user=(await response.json()).user;if(user.role!=='ventas')return location.href=user.role==='administracion'?'/admin':'/cuenta';if(user.mustChangePassword)document.querySelector('#password-change-note').textContent='Mantén tu cuenta protegida actualizando tu contraseña cuando lo necesites.';await loadOrderOptions();loadQuotes();loadOrders()})();
