const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const database = require('../base_de_datos/base_de_datos');
const email = require('./correo');
const { createAnalyticsService } = require('./analytics/analytics-service');
const analytics = createAnalyticsService({ getBusinessSnapshot: database.getAnalyticsSnapshot });

const port = Number(process.env.PORT || 3000);
const frontendPath = path.join(__dirname, '..', 'frontend');
const allowedStatuses = ['Pedido en curso', 'Pedido en camino', 'Pedido entregado', 'Cancelado'];
const sessions = new Map();
const sessionDurationMs = 8 * 60 * 60 * 1000;

function sendJson(response, status, data) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(data)); }
function serveFile(response, fileName, contentType) { fs.readFile(path.join(frontendPath, fileName), (error, content) => { if (error) { response.writeHead(404); response.end('No encontrado'); return; } response.writeHead(200, { 'Content-Type': contentType }); response.end(content); }); }
function serveDataImage(response, image) { const match = String(image || '').match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/); if (!match) { response.writeHead(404); response.end('Imagen no encontrada'); return; } response.writeHead(200, { 'Content-Type': match[1], 'Cache-Control': 'public, max-age=86400' }); response.end(Buffer.from(match[2], 'base64')); }
function serveImage(response, image) { if (String(image || '').startsWith('data:image/')) return serveDataImage(response, image); const file = database.getMediaFile(image); if (!file) { response.writeHead(404); response.end('Imagen no encontrada'); return; } response.writeHead(200, { 'Content-Type': file.mime, 'Cache-Control': 'public, max-age=31536000, immutable' }); fs.createReadStream(file.path).on('error', () => { if (!response.headersSent) response.writeHead(404); response.end('Imagen no encontrada'); }).pipe(response); }
function readBody(request) { return new Promise((resolve, reject) => { let body = ''; request.on('data', (chunk) => { body += chunk; }); request.on('end', () => { try { resolve(JSON.parse(body || '{}')); } catch { reject(new Error('Datos inválidos')); } }); }); }
function readRawBody(request, maximumBytes) { return new Promise((resolve, reject) => { const chunks = []; let size = 0; request.on('data', (chunk) => { size += chunk.length; if (size > maximumBytes) { reject(new Error('El archivo PDF supera el máximo permitido de 5 MB.')); request.destroy(); return; } chunks.push(chunk); }); request.on('end', () => resolve(Buffer.concat(chunks))); request.on('error', reject); }); }
async function readJobApplication(request) { const type = String(request.headers['content-type'] || ''); const boundaryMatch = type.match(/boundary=(?:"([^"]+)"|([^;\s]+))/i); const boundary = boundaryMatch?.[1] || boundaryMatch?.[2]; if (!boundary) throw new Error('No pudimos leer el formulario.'); const raw = await readRawBody(request, 5 * 1024 * 1024 + 64 * 1024); const separator = Buffer.from(`--${boundary}`); const values = {}; let file = null; let offset = raw.indexOf(separator) + separator.length + 2; while (offset > separator.length + 1 && offset < raw.length) { const next = raw.indexOf(separator, offset); if (next < 0) break; const part = raw.subarray(offset, next - 2); const divider = part.indexOf(Buffer.from('\r\n\r\n')); if (divider >= 0) { const headers = part.subarray(0, divider).toString('utf8'); const content = part.subarray(divider + 4); const name = headers.match(/name="([^"]+)"/i)?.[1]; const filename = headers.match(/filename="([^"]*)"/i)?.[1]; if (name === 'cv') file = { name: filename || 'cv.pdf', type: headers.match(/Content-Type:\s*([^\r\n]+)/i)?.[1]?.trim().toLowerCase() || '', content }; else if (name) values[name] = content.toString('utf8').trim(); } offset = next + separator.length + 2; }
  return { ...values, cv: file };
}
function validateClient(client) {
  if (!client.name || !client.email) return 'Completa nombre y correo.';
  if (!/^\d{9}$/.test(String(client.phone || ''))) return 'El teléfono debe tener exactamente 9 dígitos.';
  if (!['DNI', 'RUC'].includes(client.documentType)) return 'Selecciona DNI o RUC.';
  const documentLength = client.documentType === 'DNI' ? 8 : 11;
  if (!new RegExp(`^\\d{${documentLength}}$`).test(String(client.documentNumber || ''))) return `El ${client.documentType} debe tener exactamente ${documentLength} dígitos.`;
  if (!client.department || !client.province) return 'Selecciona departamento y provincia.';
  if (!client.district || !client.address) return 'Completa distrito y dirección.';
  return null;
}
function validateSalesUser(user, requiresTemporaryPassword = true) {
  if (!user.name || !user.email) return 'Completa nombre y correo.';
  if (!/^\d{9}$/.test(String(user.phone || ''))) return 'El teléfono debe tener exactamente 9 dígitos.';
  if (!/^\d{8,11}$/.test(String(user.documentNumber || ''))) return 'El número de documento debe tener entre 8 y 11 dígitos.';
  if (requiresTemporaryPassword && (!user.temporaryPassword || user.temporaryPassword.length < 8)) return 'La contraseña temporal debe tener al menos 8 caracteres.';
  return null;
}
function validateSocialNetworks(networks) {
  for (const value of [networks.facebookUrl, networks.instagramUrl, networks.linkedinUrl]) {
    if (!value) continue;
    try { const url = new URL(value); if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Protocol'); } catch { return 'Ingresa enlaces completos que comiencen con https://.'; }
  }
  return null;
}
function normalizeAttentionSchedule(value) { const match = String(value || '').trim().toLowerCase().match(/^([1-9]|1[0-2])\s?(am|pm)\s+a\s+([1-9]|1[0-2])\s?(am|pm)$/); return match ? `${Number(match[1])}${match[2]} a ${Number(match[3])}${match[4]}` : null; }
function isImageValue(value) { return /^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(String(value || '')) || /^\/media\/(?:banners|partners|categories|products|timeline|about)\/[a-f0-9-]+\.(?:png|jpg|webp)$/.test(String(value || '')); }
function validateAboutSettings(settings) { const description = String(settings.description || '').trim(); const image = String(settings.image || ''); if (!description) return 'Ingresa el texto descriptivo de Sobre nosotros.'; if (description.length > 2000) return 'El texto descriptivo no puede superar los 2000 caracteres.'; if (image && !isImageValue(image)) return 'Carga una imagen PNG, JPG o WebP válida.'; return null; }
function validateJobApplicationDetails(data) { const documentType = String(data.documentType || ''); const length = documentType === 'DNI' ? 8 : documentType === 'CE' ? 9 : 0; if (!length || !new RegExp(`^\\d{${length}}$`).test(String(data.dni || ''))) return documentType === 'CE' ? 'Ingresa un Carnet de Extranjería válido de 9 dígitos.' : 'Ingresa un DNI válido de 8 dígitos.'; if (!String(data.firstName || '').trim() || !String(data.lastName || '').trim()) return 'Completa nombres y apellidos.'; return null; }
function validateJobApplication(data) { const error = validateJobApplicationDetails(data); if (error) return error; if (!data.cv || !/\.pdf$/i.test(data.cv.name) || data.cv.type !== 'application/pdf' || !data.cv.content.subarray(0, 5).equals(Buffer.from('%PDF-'))) return 'Adjunta un CV válido en formato PDF.'; return null; }
function getSession(request) { const token = (request.headers.cookie || '').split(';').map((item) => item.trim()).find((item) => item.startsWith('mvp_session='))?.split('=')[1]; const record = token ? sessions.get(token) : null; if (!record) return null; if (record.expiresAt < Date.now()) { sessions.delete(token); return null; } return record.user; }
function requireRole(request, response, role) { const session = getSession(request); if (!session || (role && session.role !== role)) { sendJson(response, 401, { message: 'Acceso no autorizado.' }); return null; } return session; }
function requireRoles(request, response, roles) { const session = getSession(request); if (!session || !roles.includes(session.role)) { sendJson(response, 401, { message: 'Acceso no autorizado.' }); return null; } return session; }
function revokeSalesUserSessions(userId) { for (const [token, record] of sessions) if (record.user.role === 'ventas' && record.user.id === userId) sessions.delete(token); }

const server = http.createServer(async (request, response) => {
  const url = new URL(request.url, `http://${request.headers.host}`);
  try {
    if (request.method === 'POST' && url.pathname === '/api/auth/login') { const credentials = await readBody(request); const user = database.authenticate(credentials.email, credentials.password); if (!user) return sendJson(response, 401, { message: 'Correo o contraseña incorrectos.' }); const token = crypto.randomUUID(); sessions.set(token, { user, expiresAt: Date.now() + sessionDurationMs }); response.setHeader('Set-Cookie', `mvp_session=${token}; HttpOnly; SameSite=Lax; Max-Age=28800; Path=/`); return sendJson(response, 200, { user }); }
    if (request.method === 'POST' && url.pathname === '/api/auth/logout') { const token = (request.headers.cookie || '').split(';').map((item) => item.trim()).find((item) => item.startsWith('mvp_session='))?.split('=')[1]; if (token) sessions.delete(token); response.setHeader('Set-Cookie', 'mvp_session=; Max-Age=0; Path=/'); return sendJson(response, 200, { message: 'Sesión cerrada.' }); }
    if (request.method === 'GET' && url.pathname === '/api/auth/me') { const session = getSession(request); return session ? sendJson(response, 200, { user: session }) : sendJson(response, 401, { message: 'Sin sesión.' }); }
    if (request.method === 'GET' && url.pathname === '/api/analytics/config') return sendJson(response, 200, { enabled: analytics.enabled() });
    if (request.method === 'POST' && url.pathname === '/api/analytics/events') { const event = await readBody(request); analytics.recordEvent(event); return sendJson(response, 202, { accepted: analytics.enabled() }); }
    if (request.method === 'GET' && url.pathname === '/api/analytics/dashboard') { if (!requireRole(request, response, 'administracion')) return; const dashboard = analytics.getDashboard(); return dashboard ? sendJson(response, 200, dashboard) : sendJson(response, 403, { message: 'El módulo de analítica está desactivado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/client') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.getClientById(session.clientId)); }
    if (request.method === 'PATCH' && url.pathname === '/api/my/client') { const session = requireRole(request, response, 'cliente'); if (!session) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 200, database.updateOwnClient(session.clientId, client)); }
    if (request.method === 'POST' && url.pathname === '/api/my/password') { const session = requireRoles(request, response, ['cliente', 'ventas']); if (!session) return; const credentials = await readBody(request); if (!credentials.password || credentials.password.length < 8) return sendJson(response, 400, { message: 'La nueva contraseña debe tener al menos 8 caracteres.' }); if (!database.changeOwnPassword(session.id, session.role, credentials.password)) return sendJson(response, 400, { message: 'No pudimos cambiar la contraseña.' }); session.mustChangePassword = false; return sendJson(response, 200, { message: 'Contraseña actualizada.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/quotes') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.listQuotesByClient(session.clientId)); }
    if (request.method === 'POST' && url.pathname === '/api/my/quotes') { const session = requireRole(request, response, 'cliente'); if (!session) return; const client = database.getClientById(session.clientId); const quote = await readBody(request); if (!quote.product) return sendJson(response, 400, { message: 'Selecciona un producto.' }); const createdQuote = database.createQuote({ name: client.name, email: client.email, product: quote.product, message: quote.message || '' }); email.notifyNewQuote(createdQuote); return sendJson(response, 201, { message: 'Cotización enviada.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/my/quotes/')) { const session = requireRole(request, response, 'cliente'); if (!session) return; const quote = database.updateOwnQuote(Number(url.pathname.split('/').pop()), session.clientId, await readBody(request)); return quote ? sendJson(response, 200, quote) : sendJson(response, 400, { message: 'Solo se pueden editar cotizaciones pendientes.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/orders') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.listOrdersByClient(session.clientId)); }
    if (request.method === 'GET' && url.pathname === '/api/products') return sendJson(response, 200, database.listProducts());
    if (request.method === 'GET' && url.pathname === '/api/categories') return sendJson(response, 200, database.listCategories());
    if (request.method === 'GET' && url.pathname === '/api/catalog') return sendJson(response, 200, database.listCatalogSummary());
    if (request.method === 'GET' && /^\/api\/catalog\/categories\/\d+\/products$/.test(url.pathname)) return sendJson(response, 200, database.listCatalogProducts(Number(url.pathname.split('/')[4])));
    if (request.method === 'GET' && /^\/api\/catalog\/categories\/\d+\/image$/.test(url.pathname)) return serveImage(response, database.getCategoryImage(Number(url.pathname.split('/')[4])));
    if (request.method === 'GET' && url.pathname.startsWith('/media/')) return serveImage(response, url.pathname.slice(1));
    if (request.method === 'GET' && url.pathname === '/api/company-settings') return sendJson(response, 200, database.getCompanySettings());
    if (request.method === 'POST' && url.pathname === '/api/job-applications') { const application = await readJobApplication(request); const error = validateJobApplication(application); if (error) return sendJson(response, 400, { message: error }); database.createJobApplication({ firstName: application.firstName, lastName: application.lastName, documentType: application.documentType, dni: application.dni, cvName: application.cv.name, cvBuffer: application.cv.content }); return sendJson(response, 201, { message: 'Tu postulación fue enviada correctamente.' }); }
    if (request.method === 'GET' && url.pathname === '/api/admin/job-applications') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listJobApplications()); }
    if (request.method === 'GET' && /^\/api\/admin\/job-applications\/\d+\/cv$/.test(url.pathname)) { if (!requireRole(request, response, 'administracion')) return; const cv = database.getJobApplicationCv(Number(url.pathname.split('/')[4])); if (!cv) return sendJson(response, 404, { message: 'CV no encontrado.' }); response.writeHead(200, { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${encodeURIComponent(cv.name)}"; filename*=UTF-8''${encodeURIComponent(cv.name)}`, 'Cache-Control': 'private, no-store' }); return fs.createReadStream(cv.path).pipe(response); }
    if (request.method === 'PATCH' && /^\/api\/admin\/job-applications\/\d+$/.test(url.pathname)) { if (!requireRole(request, response, 'administracion')) return; const application = await readBody(request); const error = validateJobApplicationDetails(application); if (error) return sendJson(response, 400, { message: error }); const updated = database.updateJobApplication(Number(url.pathname.split('/').pop()), application); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Postulación no encontrada.' }); }
    if (request.method === 'DELETE' && /^\/api\/admin\/job-applications\/\d+$/.test(url.pathname)) { if (!requireRole(request, response, 'administracion')) return; return database.deleteJobApplication(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Postulación eliminada.' }) : sendJson(response, 404, { message: 'Postulación no encontrada.' }); }
    if (request.method === 'GET' && url.pathname === '/api/about') return sendJson(response, 200, database.getAboutSettings());
    if (request.method === 'GET' && url.pathname === '/api/about/image') return serveImage(response, database.getAboutImage());
    if (request.method === 'GET' && url.pathname === '/api/admin/about') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.getAboutSettingsAdmin()); }
    if (request.method === 'PATCH' && url.pathname === '/api/admin/about') { if (!requireRole(request, response, 'administracion')) return; const settings = await readBody(request); const error = validateAboutSettings(settings); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 200, database.updateAboutSettings({ description: String(settings.description).trim(), image: String(settings.image || '') })); }
    if (request.method === 'GET' && url.pathname === '/api/email/test-status') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, email.getEmailConfigurationStatus()); }
    if (request.method === 'PATCH' && url.pathname === '/api/email/configuration') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, email.saveEmailConfiguration(await readBody(request))); }
    if (request.method === 'POST' && url.pathname === '/api/email/send-test') { if (!requireRole(request, response, 'administracion')) return; await email.sendTestEmail(); return sendJson(response, 200, { message: 'Correo de prueba enviado. Revisa tu bandeja de entrada y la carpeta de spam.' }); }
    if (request.method === 'GET' && url.pathname === '/api/email/templates') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, email.getEmailTemplates()); }
    if (request.method === 'PATCH' && url.pathname === '/api/email/templates/signature') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, { signature: email.saveEmailSignature((await readBody(request)).signature) }); }
    if (request.method === 'PATCH' && /^\/api\/email\/templates\/[a-z_]+$/.test(url.pathname)) { if (!requireRole(request, response, 'administracion')) return; const type = url.pathname.split('/').pop(); return sendJson(response, 200, email.saveEmailTemplate(type, await readBody(request))); }
    if (request.method === 'POST' && /^\/api\/email\/templates\/[a-z_]+\/send-test$/.test(url.pathname)) { if (!requireRole(request, response, 'administracion')) return; const type = url.pathname.split('/')[4]; await email.sendTemplateTest(type); return sendJson(response, 200, { message: 'Prueba enviada con la plantilla seleccionada. Revisa la bandeja de entrada y spam.' }); }
    if (request.method === 'PATCH' && url.pathname === '/api/company-settings') { if (!requireRole(request, response, 'administracion')) return; const settings = await readBody(request); const whatsAppNumber = String(settings.whatsappNumber || '').replace(/\D/g, ''); const contactPhone = String(settings.contactPhone || '').trim(); const contactEmail = String(settings.contactEmail || '').trim().toLowerCase(); const contactDigits = contactPhone.replace(/\D/g, ''); if (whatsAppNumber && !/^\d{8,15}$/.test(whatsAppNumber)) return sendJson(response, 400, { message: 'Ingresa un número de WhatsApp válido, con código de país.' }); if (contactPhone && (!/^[0-9+()\-\s]+$/.test(contactPhone) || contactDigits.length < 7 || contactDigits.length > 15)) return sendJson(response, 400, { message: 'Ingresa un teléfono de contacto válido.' }); if (contactEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contactEmail)) return sendJson(response, 400, { message: 'Ingresa un correo de contacto válido.' }); return sendJson(response, 200, database.updateContactNumbers(whatsAppNumber, contactPhone, contactEmail)); }
    if (request.method === 'PATCH' && url.pathname === '/api/company-settings/social-networks') { if (!requireRole(request, response, 'administracion')) return; const networks = await readBody(request); const error = validateSocialNetworks(networks); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 200, database.updateSocialNetworks(networks)); }
    if (request.method === 'GET' && url.pathname === '/api/kpis') return sendJson(response, 200, database.getKpis());
    if (request.method === 'GET' && url.pathname === '/api/attention-points') return sendJson(response, 200, database.listAttentionPoints());
    if (request.method === 'GET' && url.pathname === '/api/maps/config') return sendJson(response, 200, { apiKey: process.env.GOOGLE_MAPS_API_KEY || '' });
    if (request.method === 'POST' && url.pathname === '/api/attention-points') { if (!requireRole(request, response, 'administracion')) return; const point = await readBody(request), schedule = normalizeAttentionSchedule(point.schedule); if (!point.name || !point.address) return sendJson(response, 400, { message: 'Completa el nombre y la dirección.' }); if (!schedule) return sendJson(response, 400, { message: 'Ingresa el horario en formato de 12 horas, por ejemplo: 7am a 6pm.' }); return sendJson(response, 201, database.createAttentionPoint({ ...point, schedule })); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/attention-points/')) { if (!requireRole(request, response, 'administracion')) return; const point = await readBody(request), schedule = normalizeAttentionSchedule(point.schedule); if (!point.name || !point.address) return sendJson(response, 400, { message: 'Completa el nombre y la dirección.' }); if (!schedule) return sendJson(response, 400, { message: 'Ingresa el horario en formato de 12 horas, por ejemplo: 7am a 6pm.' }); const updated = database.updateAttentionPoint(Number(url.pathname.split('/').pop()), { ...point, schedule }); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Punto de atención no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/attention-points/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteAttentionPoint(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Punto eliminado.' }) : sendJson(response, 404, { message: 'Punto de atención no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/banners') return sendJson(response, 200, database.listBanners());
    if (request.method === 'GET' && /^\/api\/banners\/\d+\/image$/.test(url.pathname)) return serveImage(response, database.getBannerImage(Number(url.pathname.split('/')[3])));
    if (request.method === 'GET' && url.pathname === '/api/admin/banners') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listBannersAdmin()); }
    if (request.method === 'POST' && url.pathname === '/api/banners') { if (!requireRole(request, response, 'administracion')) return; const banner = await readBody(request); if (!isImageValue(banner.image)) return sendJson(response, 400, { message: 'Carga una imagen válida para el banner.' }); database.createBanner(banner); return sendJson(response, 201, { message: 'Imagen agregada.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/banners/')) { if (!requireRole(request, response, 'administracion')) return; const banner = await readBody(request); if (!isImageValue(banner.image)) return sendJson(response, 400, { message: 'Carga una imagen válida para el banner.' }); const updated = database.updateBanner(Number(url.pathname.split('/').pop()), banner); return updated ? sendJson(response, 200, { message: 'Imagen actualizada.' }) : sendJson(response, 404, { message: 'Banner no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/banners/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteBanner(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Banner eliminado.' }) : sendJson(response, 404, { message: 'Banner no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/commercial-partners') return sendJson(response, 200, database.listCommercialPartners());
    if (request.method === 'POST' && url.pathname === '/api/commercial-partners') { if (!requireRole(request, response, 'administracion')) return; const partner = await readBody(request); if (!partner.name || !isImageValue(partner.image)) return sendJson(response, 400, { message: 'Completa el nombre y carga un logo válido.' }); return sendJson(response, 201, database.createCommercialPartner(partner)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/commercial-partners/')) { if (!requireRole(request, response, 'administracion')) return; const partner = await readBody(request); if (!partner.name || !isImageValue(partner.image)) return sendJson(response, 400, { message: 'Completa el nombre y carga un logo válido.' }); const updated = database.updateCommercialPartner(Number(url.pathname.split('/').pop()), partner); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Socio no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/commercial-partners/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteCommercialPartner(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Socio eliminado.' }) : sendJson(response, 404, { message: 'Socio no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/timeline') return sendJson(response, 200, database.listTimelineItems());
    if (request.method === 'POST' && url.pathname === '/api/timeline') { if (!requireRole(request, response, 'administracion')) return; const item = await readBody(request); if (!/^\d{4}$/.test(String(item.year || '')) || !item.title || !item.text) return sendJson(response, 400, { message: 'Completa año, título y descripción.' }); return sendJson(response, 201, database.createTimelineItem(item)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/timeline/')) { if (!requireRole(request, response, 'administracion')) return; const item = await readBody(request); if (!/^\d{4}$/.test(String(item.year || '')) || !item.title || !item.text) return sendJson(response, 400, { message: 'Completa año, título y descripción.' }); const updated = database.updateTimelineItem(Number(url.pathname.split('/').pop()), item); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Hito no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/timeline/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteTimelineItem(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Hito eliminado.' }) : sendJson(response, 404, { message: 'Hito no encontrado.' }); }
    if (request.method === 'PATCH' && url.pathname === '/api/company-settings/experience-kpis') { if (!requireRole(request, response, 'administracion')) return; const settings = await readBody(request); const fields = ['experienceValue', 'experienceDescription', 'productsValue', 'productsDescription', 'clientsValue', 'clientsDescription']; if (fields.some((field) => !String(settings[field] || '').trim() || String(settings[field]).length > 120)) return sendJson(response, 400, { message: 'Completa el valor y la descripción de cada indicador (máximo 120 caracteres).' }); return sendJson(response, 200, database.updateExperienceKpis(settings)); }
    if (request.method === 'GET' && url.pathname === '/api/additional-kpis') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listAdditionalKpis()); }
    if (request.method === 'POST' && url.pathname === '/api/additional-kpis') { if (!requireRole(request, response, 'administracion')) return; const kpi = await readBody(request); if (!kpi.title || !kpi.value) return sendJson(response, 400, { message: 'Completa título y valor del indicador.' }); return sendJson(response, 201, database.createAdditionalKpi(kpi)); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/additional-kpis/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteAdditionalKpi(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Indicador eliminado.' }) : sendJson(response, 404, { message: 'Indicador no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/order-options') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, { products: database.listProducts(), units: database.listUnits() }); }
    if (request.method === 'POST' && url.pathname === '/api/categories') { if (!requireRole(request, response, 'administracion')) return; const category = await readBody(request); if (!category.name) return sendJson(response, 400, { message: 'Completa el nombre de la categoría.' }); return sendJson(response, 201, database.createCategory(category)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/categories/')) { if (!requireRole(request, response, 'administracion')) return; const category = await readBody(request); if (!category.name) return sendJson(response, 400, { message: 'Completa el nombre de la categoría.' }); const updated = database.updateCategory(Number(url.pathname.split('/').pop()), category); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Categoría no encontrada.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/categories/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteCategory(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Categoría eliminada.' }) : sendJson(response, 404, { message: 'Categoría no encontrada.' }); }
    if (request.method === 'POST' && url.pathname === '/api/products') { if (!requireRole(request, response, 'administracion')) return; const product = await readBody(request); if (!product.name || !product.categoryId) return sendJson(response, 400, { message: 'Completa nombre y categoría.' }); return sendJson(response, 201, database.createProduct(product)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/products/')) { if (!requireRole(request, response, 'administracion')) return; const product = await readBody(request); if (!product.name || !product.categoryId) return sendJson(response, 400, { message: 'Completa nombre y categoría.' }); const updated = database.updateProduct(Number(url.pathname.split('/').pop()), product); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Producto no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/products/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteProduct(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Producto eliminado.' }) : sendJson(response, 404, { message: 'Producto no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/clients') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listClients()); }
    if (request.method === 'POST' && url.pathname === '/api/clients') { if (!requireRole(request, response, 'administracion')) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); if (!client.temporaryPassword || client.temporaryPassword.length < 8) return sendJson(response, 400, { message: 'La contraseña temporal debe tener al menos 8 caracteres.' }); return sendJson(response, 201, database.createClient(client)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/clients/')) { if (!requireRole(request, response, 'administracion')) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); const updated = database.updateClient(Number(url.pathname.split('/').pop()), client); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Cliente no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/clients/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteClient(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Cliente eliminado.' }) : sendJson(response, 404, { message: 'Cliente no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/sales-users') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listSalesUsers()); }
    if (request.method === 'POST' && url.pathname === '/api/sales-users') { if (!requireRole(request, response, 'administracion')) return; const user = await readBody(request); const error = validateSalesUser(user); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 201, database.createSalesUser(user)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/sales-users/')) { if (!requireRole(request, response, 'administracion')) return; const user = await readBody(request); const error = validateSalesUser(user, false); if (error) return sendJson(response, 400, { message: error }); const updated = database.updateSalesUser(Number(url.pathname.split('/').pop()), user); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Usuario de ventas no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/sales-users/')) { if (!requireRole(request, response, 'administracion')) return; const id = Number(url.pathname.split('/').pop()); if (!database.deleteSalesUser(id)) return sendJson(response, 404, { message: 'Usuario de ventas no encontrado.' }); revokeSalesUserSessions(id); return sendJson(response, 200, { message: 'Usuario de ventas eliminado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/orders') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, database.listOrders()); }
    if (request.method === 'GET' && url.pathname.startsWith('/api/orders/')) { const session = getSession(request); if (!session) return sendJson(response, 401, { message: 'Inicia sesión para consultar un pedido.' }); const code = decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); const order = session.role === 'administracion' ? database.getOrderByCode(code) : database.listOrdersByClient(session.clientId).find((item) => item.code === code); return order ? sendJson(response, 200, order) : sendJson(response, 404, { message: 'No encontramos ese pedido asociado a tu cuenta.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/orders/')) { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; const update = await readBody(request); if (!allowedStatuses.includes(update.status)) return sendJson(response, 400, { message: 'Actualización inválida.' }); const code = decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); const previous = database.getOrderByCode(code); const order = database.updateOrderStatus(code, update.status); if (order && update.status === 'Pedido en camino' && previous?.status !== 'Pedido en camino') email.notifyOrderInTransit(order).catch((error) => console.log(`No se pudo notificar el pedido ${order.code}: ${error.message}`)); return order ? sendJson(response, 200, order) : sendJson(response, 404, { message: 'Pedido no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/quotes') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, database.listQuotes()); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/quotes/')) { if (!requireRole(request, response, 'administracion')) return; const quote = database.updateQuoteAdmin(Number(url.pathname.split('/').pop()), await readBody(request)); return quote ? sendJson(response, 200, quote) : sendJson(response, 400, { message: 'Solo se pueden editar cotizaciones pendientes.' }); }
    if (request.method === 'POST' && /^\/api\/quotes\/\d+\/orders$/.test(url.pathname)) { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; const details = await readBody(request); if (!details.product || !details.quantity || !details.price || !details.unit || !details.estimatedDeliveryDate) return sendJson(response, 400, { message: 'Completa todos los datos del pedido.' }); const order = database.createOrderFromQuote(Number(url.pathname.split('/')[3]), details); email.notifyOrderCreated(order).catch((error) => console.log(`No se pudo notificar el pedido ${order.code}: ${error.message}`)); return sendJson(response, 201, { message: 'Pedido creado.', order }); }
    if (request.method === 'POST' && url.pathname === '/api/quotes') { const quote = await readBody(request); const session = getSession(request); const client = session?.role === 'cliente' ? database.getClientById(session.clientId) : null; const quoteData = client ? { ...quote, name: client.name, email: client.email } : quote; if (!quoteData.name || !quoteData.email || !quoteData.product) return sendJson(response, 400, { message: 'Completa nombre, correo y producto.' }); const createdQuote = database.createQuote(quoteData); email.notifyNewQuote(createdQuote); return sendJson(response, 201, { message: 'Recibimos tu solicitud. Te contactaremos pronto.' }); }
    if (request.method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) return serveFile(response, 'index.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/login') return serveFile(response, 'login.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/cuenta') return serveFile(response, 'cuenta.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/ventas') { const session = getSession(request); if (!session) { response.writeHead(302, { Location: '/login' }); return response.end(); } if (session.role !== 'ventas') { response.writeHead(302, { Location: session.role === 'administracion' ? '/admin' : '/cuenta' }); return response.end(); } return serveFile(response, 'ventas.html', 'text/html; charset=utf-8'); }
    if (request.method === 'GET' && url.pathname === '/admin') { const session = getSession(request); if (!session) { response.writeHead(302, { Location: '/login' }); return response.end(); } if (session.role !== 'administracion') { response.writeHead(302, { Location: '/cuenta' }); return response.end(); } return serveFile(response, 'admin.html', 'text/html; charset=utf-8'); }
    if (request.method === 'GET' && url.pathname === '/styles.css') return serveFile(response, 'styles.css', 'text/css; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/app.js') return serveFile(response, 'app.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/admin.js') return serveFile(response, 'admin.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/login.js') return serveFile(response, 'login.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/cuenta.js') return serveFile(response, 'cuenta.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/ventas.js') return serveFile(response, 'ventas.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/assets/almacen-costa-grande.png') return serveFile(response, 'assets/almacen-costa-grande.png', 'image/png');
    if (request.method === 'GET' && url.pathname === '/assets/logo-negocios-costa-grande.png') return serveFile(response, 'assets/logo-negocios-costa-grande.png', 'image/png');
    if (request.method === 'GET' && url.pathname === '/assets/catalog-loading-groceries-v3.webp') return serveFile(response, 'assets/catalog-loading-groceries-v3.webp', 'image/webp');
    response.writeHead(404); response.end('No encontrado');
  } catch (error) { sendJson(response, 400, { message: error.message || 'No pudimos procesar la solicitud.' }); }
});
server.listen(port, () => console.log(`MVP listo en http://localhost:${port}`));
