const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const database = require('../base_de_datos/base_de_datos');
const email = require('./correo');

const port = 3000;
const frontendPath = path.join(__dirname, '..', 'frontend');
const allowedStatuses = ['Pedido en curso', 'Pedido en camino', 'Pedido entregado', 'Cancelado'];
const sessions = new Map();
const sessionDurationMs = 8 * 60 * 60 * 1000;

function sendJson(response, status, data) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(data)); }
function serveFile(response, fileName, contentType) { fs.readFile(path.join(frontendPath, fileName), (error, content) => { if (error) { response.writeHead(404); response.end('No encontrado'); return; } response.writeHead(200, { 'Content-Type': contentType }); response.end(content); }); }
function readBody(request) { return new Promise((resolve, reject) => { let body = ''; request.on('data', (chunk) => { body += chunk; }); request.on('end', () => { try { resolve(JSON.parse(body || '{}')); } catch { reject(new Error('Datos inválidos')); } }); }); }
function validateClient(client) {
  if (!client.name || !client.email) return 'Completa nombre y correo.';
  if (!/^\d{9}$/.test(String(client.phone || ''))) return 'El teléfono debe tener exactamente 9 dígitos.';
  if (!['DNI', 'RUC'].includes(client.documentType)) return 'Selecciona DNI o RUC.';
  const documentLength = client.documentType === 'DNI' ? 8 : 11;
  if (!new RegExp(`^\\d{${documentLength}}$`).test(String(client.documentNumber || ''))) return `El ${client.documentType} debe tener exactamente ${documentLength} dígitos.`;
  if (!client.department || !client.province) return 'Selecciona departamento y provincia.';
  if (!client.district || !client.address) return 'Completa distrito y dirección.';
  return null;
}
function validateSalesUser(user) {
  if (!user.name || !user.email || !user.userCode) return 'Completa nombre, correo y código de usuario.';
  if (!/^\d{9}$/.test(String(user.phone || ''))) return 'El teléfono debe tener exactamente 9 dígitos.';
  if (!/^\d{8,11}$/.test(String(user.documentNumber || ''))) return 'El número de documento debe tener entre 8 y 11 dígitos.';
  if (!user.temporaryPassword || user.temporaryPassword.length < 8) return 'La contraseña temporal debe tener al menos 8 caracteres.';
  return null;
}
function getSession(request) { const token = (request.headers.cookie || '').split(';').map((item) => item.trim()).find((item) => item.startsWith('mvp_session='))?.split('=')[1]; const record = token ? sessions.get(token) : null; if (!record) return null; if (record.expiresAt < Date.now()) { sessions.delete(token); return null; } return record.user; }
function requireRole(request, response, role) { const session = getSession(request); if (!session || (role && session.role !== role)) { sendJson(response, 401, { message: 'Acceso no autorizado.' }); return null; } return session; }
function requireRoles(request, response, roles) { const session = getSession(request); if (!session || !roles.includes(session.role)) { sendJson(response, 401, { message: 'Acceso no autorizado.' }); return null; } return session; }

const server = http.createServer(async (request, response) => {
  const url = new URL(request.url, `http://${request.headers.host}`);
  try {
    if (request.method === 'POST' && url.pathname === '/api/auth/login') { const credentials = await readBody(request); const user = database.authenticate(credentials.email, credentials.password); if (!user) return sendJson(response, 401, { message: 'Correo o contraseña incorrectos.' }); const token = crypto.randomUUID(); sessions.set(token, { user, expiresAt: Date.now() + sessionDurationMs }); response.setHeader('Set-Cookie', `mvp_session=${token}; HttpOnly; SameSite=Lax; Max-Age=28800; Path=/`); return sendJson(response, 200, { user }); }
    if (request.method === 'POST' && url.pathname === '/api/auth/logout') { const token = (request.headers.cookie || '').split(';').map((item) => item.trim()).find((item) => item.startsWith('mvp_session='))?.split('=')[1]; if (token) sessions.delete(token); response.setHeader('Set-Cookie', 'mvp_session=; Max-Age=0; Path=/'); return sendJson(response, 200, { message: 'Sesión cerrada.' }); }
    if (request.method === 'GET' && url.pathname === '/api/auth/me') { const session = getSession(request); return session ? sendJson(response, 200, { user: session }) : sendJson(response, 401, { message: 'Sin sesión.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/client') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.getClientById(session.clientId)); }
    if (request.method === 'PATCH' && url.pathname === '/api/my/client') { const session = requireRole(request, response, 'cliente'); if (!session) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 200, database.updateOwnClient(session.clientId, client)); }
    if (request.method === 'POST' && url.pathname === '/api/my/password') { const session = requireRoles(request, response, ['cliente', 'ventas']); if (!session) return; const credentials = await readBody(request); if (!credentials.password || credentials.password.length < 8) return sendJson(response, 400, { message: 'La nueva contraseña debe tener al menos 8 caracteres.' }); if (!database.changeOwnPassword(session.id, session.role, credentials.password)) return sendJson(response, 400, { message: 'No pudimos cambiar la contraseña.' }); session.mustChangePassword = false; return sendJson(response, 200, { message: 'Contraseña actualizada.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/quotes') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.listQuotesByClient(session.clientId)); }
    if (request.method === 'POST' && url.pathname === '/api/my/quotes') { const session = requireRole(request, response, 'cliente'); if (!session) return; const client = database.getClientById(session.clientId); const quote = await readBody(request); if (!quote.product) return sendJson(response, 400, { message: 'Selecciona un producto.' }); const createdQuote = database.createQuote({ name: client.name, email: client.email, product: quote.product, message: quote.message || '' }); email.notifyNewQuote(createdQuote); return sendJson(response, 201, { message: 'Cotización enviada.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/my/quotes/')) { const session = requireRole(request, response, 'cliente'); if (!session) return; const quote = database.updateOwnQuote(Number(url.pathname.split('/').pop()), session.clientId, await readBody(request)); return quote ? sendJson(response, 200, quote) : sendJson(response, 400, { message: 'Solo se pueden editar cotizaciones pendientes.' }); }
    if (request.method === 'GET' && url.pathname === '/api/my/orders') { const session = requireRole(request, response, 'cliente'); return session && sendJson(response, 200, database.listOrdersByClient(session.clientId)); }
    if (request.method === 'GET' && url.pathname === '/api/products') return sendJson(response, 200, database.listProducts());
    if (request.method === 'GET' && url.pathname === '/api/company-settings') return sendJson(response, 200, database.getCompanySettings());
    if (request.method === 'GET' && url.pathname === '/api/email/test-status') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, email.getEmailConfigurationStatus()); }
    if (request.method === 'PATCH' && url.pathname === '/api/email/configuration') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, email.saveEmailConfiguration(await readBody(request))); }
    if (request.method === 'POST' && url.pathname === '/api/email/send-test') { if (!requireRole(request, response, 'administracion')) return; await email.sendTestEmail(); return sendJson(response, 200, { message: 'Correo de prueba enviado. Revisa tu bandeja de entrada y la carpeta de spam.' }); }
    if (request.method === 'PATCH' && url.pathname === '/api/company-settings') { if (!requireRole(request, response, 'administracion')) return; const settings = await readBody(request); const number = String(settings.whatsappNumber || '').replace(/\D/g, ''); if (number && !/^\d{8,15}$/.test(number)) return sendJson(response, 400, { message: 'Ingresa un número de WhatsApp válido, con código de país.' }); return sendJson(response, 200, database.updateWhatsAppNumber(number)); }
    if (request.method === 'GET' && url.pathname === '/api/kpis') return sendJson(response, 200, database.getKpis());
    if (request.method === 'GET' && url.pathname === '/api/banners') return sendJson(response, 200, database.listBanners());
    if (request.method === 'GET' && url.pathname === '/api/admin/banners') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listBannersAdmin()); }
    if (request.method === 'POST' && url.pathname === '/api/banners') { if (!requireRole(request, response, 'administracion')) return; const banner = await readBody(request); if (!String(banner.image || '').startsWith('data:image/')) return sendJson(response, 400, { message: 'Carga una imagen válida para el banner.' }); database.createBanner(banner); return sendJson(response, 201, { message: 'Imagen agregada.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/banners/')) { if (!requireRole(request, response, 'administracion')) return; const banner = await readBody(request); if (!String(banner.image || '').startsWith('data:image/')) return sendJson(response, 400, { message: 'Carga una imagen válida para el banner.' }); const updated = database.updateBanner(Number(url.pathname.split('/').pop()), banner); return updated ? sendJson(response, 200, { message: 'Imagen actualizada.' }) : sendJson(response, 404, { message: 'Banner no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/banners/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteBanner(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Banner eliminado.' }) : sendJson(response, 404, { message: 'Banner no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/timeline') return sendJson(response, 200, database.listTimelineItems());
    if (request.method === 'POST' && url.pathname === '/api/timeline') { if (!requireRole(request, response, 'administracion')) return; const item = await readBody(request); if (!/^\d{4}$/.test(String(item.year || '')) || !item.title || !item.text) return sendJson(response, 400, { message: 'Completa año, título y descripción.' }); return sendJson(response, 201, database.createTimelineItem(item)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/timeline/')) { if (!requireRole(request, response, 'administracion')) return; const item = await readBody(request); if (!/^\d{4}$/.test(String(item.year || '')) || !item.title || !item.text) return sendJson(response, 400, { message: 'Completa año, título y descripción.' }); const updated = database.updateTimelineItem(Number(url.pathname.split('/').pop()), item); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Hito no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/timeline/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteTimelineItem(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Hito eliminado.' }) : sendJson(response, 404, { message: 'Hito no encontrado.' }); }
    if (request.method === 'PATCH' && url.pathname === '/api/company-settings/historical-clients') { if (!requireRole(request, response, 'administracion')) return; const settings = await readBody(request); if (!/^\d+$/.test(String(settings.historicalClients || ''))) return sendJson(response, 400, { message: 'Ingresa una cantidad histórica válida.' }); return sendJson(response, 200, database.updateHistoricalClients(settings.historicalClients)); }
    if (request.method === 'GET' && url.pathname === '/api/additional-kpis') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listAdditionalKpis()); }
    if (request.method === 'POST' && url.pathname === '/api/additional-kpis') { if (!requireRole(request, response, 'administracion')) return; const kpi = await readBody(request); if (!kpi.title || !kpi.value) return sendJson(response, 400, { message: 'Completa título y valor del indicador.' }); return sendJson(response, 201, database.createAdditionalKpi(kpi)); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/additional-kpis/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteAdditionalKpi(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Indicador eliminado.' }) : sendJson(response, 404, { message: 'Indicador no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/order-options') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, { products: database.listProducts(), units: database.listUnits() }); }
    if (request.method === 'POST' && url.pathname === '/api/products') { if (!requireRole(request, response, 'administracion')) return; const product = await readBody(request); if (!product.name || !product.category || !product.description) return sendJson(response, 400, { message: 'Completa nombre, categoría y descripción.' }); return sendJson(response, 201, database.createProduct(product)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/products/')) { if (!requireRole(request, response, 'administracion')) return; const product = await readBody(request); const updated = database.updateProduct(Number(url.pathname.split('/').pop()), product); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Producto no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/products/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteProduct(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Producto eliminado.' }) : sendJson(response, 404, { message: 'Producto no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/clients') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listClients()); }
    if (request.method === 'POST' && url.pathname === '/api/clients') { if (!requireRole(request, response, 'administracion')) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); if (!client.temporaryPassword || client.temporaryPassword.length < 8) return sendJson(response, 400, { message: 'La contraseña temporal debe tener al menos 8 caracteres.' }); return sendJson(response, 201, database.createClient(client)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/clients/')) { if (!requireRole(request, response, 'administracion')) return; const client = await readBody(request); const error = validateClient(client); if (error) return sendJson(response, 400, { message: error }); const updated = database.updateClient(Number(url.pathname.split('/').pop()), client); return updated ? sendJson(response, 200, updated) : sendJson(response, 404, { message: 'Cliente no encontrado.' }); }
    if (request.method === 'DELETE' && url.pathname.startsWith('/api/clients/')) { if (!requireRole(request, response, 'administracion')) return; return database.deleteClient(Number(url.pathname.split('/').pop())) ? sendJson(response, 200, { message: 'Cliente eliminado.' }) : sendJson(response, 404, { message: 'Cliente no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/sales-users') { if (!requireRole(request, response, 'administracion')) return; return sendJson(response, 200, database.listSalesUsers()); }
    if (request.method === 'POST' && url.pathname === '/api/sales-users') { if (!requireRole(request, response, 'administracion')) return; const user = await readBody(request); const error = validateSalesUser(user); if (error) return sendJson(response, 400, { message: error }); return sendJson(response, 201, database.createSalesUser(user)); }
    if (request.method === 'GET' && url.pathname === '/api/orders') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, database.listOrders()); }
    if (request.method === 'GET' && url.pathname.startsWith('/api/orders/')) { const session = getSession(request); if (!session) return sendJson(response, 401, { message: 'Inicia sesión para consultar un pedido.' }); const code = decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); const order = session.role === 'administracion' ? database.getOrderByCode(code) : database.listOrdersByClient(session.clientId).find((item) => item.code === code); return order ? sendJson(response, 200, order) : sendJson(response, 404, { message: 'No encontramos ese pedido asociado a tu cuenta.' }); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/orders/')) { if (!requireRole(request, response, 'administracion')) return; const update = await readBody(request); if (!allowedStatuses.includes(update.status)) return sendJson(response, 400, { message: 'Actualización inválida.' }); const code = decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); const previous = database.getOrderByCode(code); const order = database.updateOrderStatus(code, update.status); if (order && update.status === 'Pedido en camino' && previous?.status !== 'Pedido en camino') email.notifyOrderInTransit(order).catch((error) => console.log(`No se pudo notificar el pedido ${order.code}: ${error.message}`)); return order ? sendJson(response, 200, order) : sendJson(response, 404, { message: 'Pedido no encontrado.' }); }
    if (request.method === 'GET' && url.pathname === '/api/quotes') { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; return sendJson(response, 200, database.listQuotes()); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/quotes/')) { if (!requireRole(request, response, 'administracion')) return; const quote = database.updateQuoteAdmin(Number(url.pathname.split('/').pop()), await readBody(request)); return quote ? sendJson(response, 200, quote) : sendJson(response, 400, { message: 'Solo se pueden editar cotizaciones pendientes.' }); }
    if (request.method === 'POST' && /^\/api\/quotes\/\d+\/orders$/.test(url.pathname)) { if (!requireRoles(request, response, ['administracion', 'ventas'])) return; const details = await readBody(request); if (!details.product || !details.quantity || !details.price || !details.unit || !details.estimatedDeliveryDate) return sendJson(response, 400, { message: 'Completa todos los datos del pedido.' }); const order = database.createOrderFromQuote(Number(url.pathname.split('/')[3]), details); email.notifyOrderCreated(order).catch((error) => console.log(`No se pudo notificar el pedido ${order.code}: ${error.message}`)); return sendJson(response, 201, { message: 'Pedido creado.', order }); }
    if (request.method === 'POST' && url.pathname === '/api/quotes') { const quote = await readBody(request); const session = getSession(request); const client = session?.role === 'cliente' ? database.getClientById(session.clientId) : null; const quoteData = client ? { ...quote, name: client.name, email: client.email } : quote; if (!quoteData.name || !quoteData.email || !quoteData.product) return sendJson(response, 400, { message: 'Completa nombre, correo y producto.' }); const createdQuote = database.createQuote(quoteData); email.notifyNewQuote(createdQuote); return sendJson(response, 201, { message: 'Recibimos tu solicitud. Te contactaremos pronto.' }); }
    if (request.method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) return serveFile(response, 'index.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/login') return serveFile(response, 'login.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/cuenta') return serveFile(response, 'cuenta.html', 'text/html; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/ventas') { const session = getSession(request); if (!session) { response.writeHead(302, { Location: '/login' }); return response.end(); } if (session.role !== 'ventas') { response.writeHead(302, { Location: session.role === 'administracion' ? '/admin' : '/cuenta' }); return response.end(); } return serveFile(response, 'ventas.html', 'text/html; charset=utf-8'); }
    if (request.method === 'GET' && url.pathname === '/admin') { const session = getSession(request); if (!session) { response.writeHead(302, { Location: '/login' }); return response.end(); } if (session.role !== 'administracion') { response.writeHead(302, { Location: '/cuenta' }); return response.end(); } return serveFile(response, 'admin.html', 'text/html; charset=utf-8'); }
    if (request.method === 'GET' && url.pathname === '/styles.css') return serveFile(response, 'styles.css', 'text/css; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/app.js') return serveFile(response, 'app.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/admin.js') return serveFile(response, 'admin.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/login.js') return serveFile(response, 'login.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/cuenta.js') return serveFile(response, 'cuenta.js', 'application/javascript; charset=utf-8');
    if (request.method === 'GET' && url.pathname === '/ventas.js') return serveFile(response, 'ventas.js', 'application/javascript; charset=utf-8');
    response.writeHead(404); response.end('No encontrado');
  } catch (error) { sendJson(response, 400, { message: error.message || 'No pudimos procesar la solicitud.' }); }
});
server.listen(port, () => console.log(`MVP listo en http://localhost:${port}`));
