const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { DatabaseSync } = require('node:sqlite');

const database = new DatabaseSync(path.join(__dirname, 'mvp_catalogo.db'));
database.exec('PRAGMA foreign_keys = ON;');
database.exec(fs.readFileSync(path.join(__dirname, 'esquema.sql'), 'utf8'));
// Mantiene compatible la base de datos que ya se creó antes de estos campos.
['departamento', 'provincia', 'distrito'].forEach((column) => {
  try { database.exec(`ALTER TABLE clientes ADD COLUMN ${column} TEXT`); } catch { /* La columna ya existe. */ }
});
try { database.exec('ALTER TABLE usuarios ADD COLUMN requiere_cambio_contrasena INTEGER NOT NULL DEFAULT 0'); } catch { /* La columna ya existe. */ }
try { database.exec('ALTER TABLE configuracion_empresa ADD COLUMN clientes_historicos INTEGER NOT NULL DEFAULT 0'); } catch { /* La columna ya existe. */ }
['facebook_url', 'instagram_url', 'linkedin_url'].forEach((column) => { try { database.exec(`ALTER TABLE configuracion_empresa ADD COLUMN ${column} TEXT`); } catch { /* La columna ya existe. */ } });
try { database.exec('ALTER TABLE configuracion_empresa ADD COLUMN telefono_contacto TEXT'); } catch { /* La columna ya existe. */ }
['id_categoria_padre INTEGER', 'imagen_url TEXT'].forEach((definition) => { try { database.exec(`ALTER TABLE categorias_producto ADD COLUMN ${definition}`); } catch { /* La columna ya existe. */ } });
['latitud', 'longitud'].forEach((column) => { try { database.exec(`ALTER TABLE puntos_atencion ADD COLUMN ${column} REAL`); } catch { /* La columna ya existe. */ } });

function nextCode(prefix, table) {
  const rows = database.prepare(`SELECT codigo FROM ${table}`).all();
  const highest = rows.reduce((max, row) => Math.max(max, Number(String(row.codigo).split('-')[1]) || 0), 0);
  return `${prefix}-${String(highest + 1).padStart(4, '0')}`;
}

function getOrCreateCategory(name) {
  const current = database.prepare('SELECT id FROM categorias_producto WHERE nombre = ? AND activo = 1').get(name);
  if (current) return current.id;
  return Number(database.prepare('INSERT INTO categorias_producto (nombre) VALUES (?)').run(name).lastInsertRowid);
}

function getDefaultUnit() {
  const current = database.prepare("SELECT id FROM unidades_medida WHERE abreviatura = 'sac' AND activo = 1").get();
  if (current) return current.id;
  return Number(database.prepare("INSERT INTO unidades_medida (nombre, abreviatura) VALUES ('Sacos', 'sac')").run().lastInsertRowid);
}
function configureOrderUnits() {
  const units = [['Sacos', 'sac'], ['Cajas', 'caj'], ['Paquetes', 'paq']];
  database.prepare("UPDATE unidades_medida SET activo = 0 WHERE abreviatura NOT IN ('sac', 'caj', 'paq')").run();
  units.forEach(([name, abbreviation]) => {
    const current = database.prepare('SELECT id FROM unidades_medida WHERE abreviatura = ?').get(abbreviation);
    if (current) database.prepare('UPDATE unidades_medida SET nombre = ?, activo = 1 WHERE id = ?').run(name, current.id);
    else database.prepare('INSERT INTO unidades_medida (nombre, abreviatura) VALUES (?, ?)').run(name, abbreviation);
  });
}
function listUnits() { return database.prepare('SELECT nombre AS name, abreviatura AS abbreviation FROM unidades_medida WHERE activo = 1 ORDER BY nombre').all(); }
function getUnitByAbbreviation(abbreviation) { const unit = database.prepare('SELECT id FROM unidades_medida WHERE abreviatura = ? AND activo = 1').get(abbreviation); if (!unit) throw new Error('Selecciona una unidad de medida válida.'); return unit.id; }
function getCompanySettings() { return database.prepare('SELECT numero_whatsapp AS whatsappNumber, telefono_contacto AS contactPhone, facebook_url AS facebookUrl, instagram_url AS instagramUrl, linkedin_url AS linkedinUrl, clientes_historicos AS historicalClients FROM configuracion_empresa WHERE id = 1').get() || { whatsappNumber: '', contactPhone: '', facebookUrl: '', instagramUrl: '', linkedinUrl: '', historicalClients: 0 }; }
function updateContactNumbers(whatsAppNumber, contactPhone) { database.prepare("INSERT INTO configuracion_empresa (id, numero_whatsapp, telefono_contacto, fecha_actualizacion) VALUES (1, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET numero_whatsapp = excluded.numero_whatsapp, telefono_contacto = excluded.telefono_contacto, fecha_actualizacion = CURRENT_TIMESTAMP").run(whatsAppNumber || null, contactPhone || null); return getCompanySettings(); }
function updateSocialNetworks(networks) { database.prepare("INSERT INTO configuracion_empresa (id, facebook_url, instagram_url, linkedin_url, fecha_actualizacion) VALUES (1, ?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET facebook_url = excluded.facebook_url, instagram_url = excluded.instagram_url, linkedin_url = excluded.linkedin_url, fecha_actualizacion = CURRENT_TIMESTAMP").run(networks.facebookUrl || null, networks.instagramUrl || null, networks.linkedinUrl || null); return getCompanySettings(); }
function updateHistoricalClients(value) { database.prepare("INSERT INTO configuracion_empresa (id, clientes_historicos, fecha_actualizacion) VALUES (1, ?, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET clientes_historicos = excluded.clientes_historicos, fecha_actualizacion = CURRENT_TIMESTAMP").run(Number(value)); return getCompanySettings(); }
function listAdditionalKpis() { return database.prepare('SELECT id, titulo AS title, valor AS value, descripcion AS description FROM kpis_adicionales WHERE activo = 1 ORDER BY id').all(); }
function createAdditionalKpi(data) { const id = Number(database.prepare('INSERT INTO kpis_adicionales (titulo, valor, descripcion) VALUES (?, ?, ?)').run(data.title, data.value, data.description || null).lastInsertRowid); return listAdditionalKpis().find((item) => item.id === id); }
function deleteAdditionalKpi(id) { return database.prepare('UPDATE kpis_adicionales SET activo = 0 WHERE id = ?').run(id).changes > 0; }
function getKpis() { const settings = getCompanySettings(); const currentClients = Number(database.prepare('SELECT COUNT(*) AS total FROM clientes WHERE activo = 1').get().total); return [{ title: 'Años de experiencia', value: `+${new Date().getFullYear() - 2005}`, description: 'Desde 2005' }, { title: 'Productos disponibles', value: `+${database.prepare('SELECT COUNT(*) AS total FROM productos WHERE activo = 1').get().total}`, description: 'En nuestro catálogo' }, { title: 'Clientes atendidos', value: `+${Number(settings.historicalClients || 0) + currentClients}`, description: 'Históricos y actuales' }, ...listAdditionalKpis()]; }
function listTimelineItems() { return database.prepare('SELECT id, anio AS year, titulo AS title, descripcion AS text, imagen_url AS image FROM hitos_historia WHERE activo = 1 ORDER BY anio').all(); }
function createTimelineItem(data) { const id = Number(database.prepare('INSERT INTO hitos_historia (anio, titulo, descripcion, imagen_url) VALUES (?, ?, ?, ?)').run(Number(data.year), data.title, data.text, data.image || null).lastInsertRowid); return listTimelineItems().find((item) => item.id === id); }
function updateTimelineItem(id, data) { const result = database.prepare('UPDATE hitos_historia SET anio = ?, titulo = ?, descripcion = ?, imagen_url = ? WHERE id = ? AND activo = 1').run(Number(data.year), data.title, data.text, data.image || null, id); return result.changes ? listTimelineItems().find((item) => item.id === id) : null; }
function deleteTimelineItem(id) { return database.prepare('UPDATE hitos_historia SET activo = 0 WHERE id = ?').run(id).changes > 0; }
function listBanners() { return database.prepare("SELECT id, imagen_url AS image FROM banners_publicitarios WHERE activo = 1 AND imagen_url IS NOT NULL AND imagen_url <> '' ORDER BY id").all(); }
function listBannersAdmin() { return database.prepare("SELECT id, imagen_url AS image FROM banners_publicitarios WHERE activo = 1 ORDER BY id").all(); }
function createBanner(data) { const id = Number(database.prepare('INSERT INTO banners_publicitarios (titulo, imagen_url) VALUES (?, ?)').run('Banner', data.image)); return listBannersAdmin().find((item) => item.id === id); }
function updateBanner(id, data) { const result = database.prepare('UPDATE banners_publicitarios SET imagen_url = ?, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ? AND activo = 1').run(data.image, id); return result.changes ? listBannersAdmin().find((item) => item.id === id) : null; }
function deleteBanner(id) { return database.prepare('UPDATE banners_publicitarios SET activo = 0, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ?').run(id).changes > 0; }
function listCommercialPartners() { return database.prepare('SELECT id, nombre AS name, imagen_url AS image FROM socios_comerciales WHERE activo = 1 ORDER BY id').all(); }
function createCommercialPartner(data) { const id = Number(database.prepare('INSERT INTO socios_comerciales (nombre, imagen_url) VALUES (?, ?)').run(data.name, data.image).lastInsertRowid); return listCommercialPartners().find((item) => item.id === id); }
function updateCommercialPartner(id, data) { const result = database.prepare('UPDATE socios_comerciales SET nombre = ?, imagen_url = ?, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ? AND activo = 1').run(data.name, data.image, id); return result.changes ? listCommercialPartners().find((item) => item.id === id) : null; }
function deleteCommercialPartner(id) { return database.prepare('UPDATE socios_comerciales SET activo = 0, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ?').run(id).changes > 0; }
function listAttentionPoints() { return database.prepare('SELECT id, nombre AS name, direccion AS address, latitud AS latitude, longitud AS longitude FROM puntos_atencion WHERE activo = 1 ORDER BY id').all(); }
function coordinate(value) { if (value === null || value === undefined || value === '') return null; const number = Number(value); return Number.isFinite(number) ? number : null; }
function createAttentionPoint(data) { const id = Number(database.prepare('INSERT INTO puntos_atencion (nombre, direccion, latitud, longitud) VALUES (?, ?, ?, ?)').run(data.name, data.address, coordinate(data.latitude), coordinate(data.longitude)).lastInsertRowid); return listAttentionPoints().find((item) => item.id === id); }
function updateAttentionPoint(id, data) { const current = database.prepare('SELECT latitud AS latitude, longitud AS longitude FROM puntos_atencion WHERE id = ? AND activo = 1').get(id); if (!current) return null; const latitude = data.latitude === undefined ? current.latitude : coordinate(data.latitude); const longitude = data.longitude === undefined ? current.longitude : coordinate(data.longitude); const result = database.prepare('UPDATE puntos_atencion SET nombre = ?, direccion = ?, latitud = ?, longitud = ?, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ? AND activo = 1').run(data.name, data.address, latitude, longitude, id); return result.changes ? listAttentionPoints().find((item) => item.id === id) : null; }
function deleteAttentionPoint(id) { return database.prepare('UPDATE puntos_atencion SET activo = 0, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ?').run(id).changes > 0; }

function getOrCreateCustomer(name, email) {
  const current = database.prepare('SELECT id FROM clientes WHERE correo = ?').get(email);
  if (current) return current.id;
  return Number(database.prepare('INSERT INTO clientes (nombre_contacto, correo) VALUES (?, ?)').run(name, email).lastInsertRowid);
}

function hashPassword(password) { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; }
function verifyPassword(password, stored) { const [salt, storedHash] = String(stored).split(':'); if (!salt || !storedHash) return false; const derived = crypto.scryptSync(password, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(storedHash, 'hex'), Buffer.from(derived, 'hex')); }

const clientFields = 'id, nombre_contacto AS name, correo AS email, telefono AS phone, razon_social AS company, tipo_documento AS documentType, numero_documento AS documentNumber, direccion AS address, departamento AS department, provincia AS province, distrito AS district';
function listClients() { return database.prepare(`SELECT ${clientFields} FROM clientes WHERE activo = 1 ORDER BY id DESC`).all(); }
function createClient(data) { database.exec('BEGIN'); try { const id = Number(database.prepare('INSERT INTO clientes (nombre_contacto, correo, telefono, razon_social, tipo_documento, numero_documento, direccion, departamento, provincia, distrito) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(data.name, data.email, data.phone || null, data.company || null, data.documentType || null, data.documentNumber || null, data.address || null, data.department || null, data.province || null, data.district || null).lastInsertRowid); database.prepare('INSERT INTO usuarios (id_cliente, correo, contrasena_hash, rol, requiere_cambio_contrasena) VALUES (?, ?, ?, ?, 1)').run(id, data.email, hashPassword(data.temporaryPassword), 'cliente'); database.exec('COMMIT'); return listClients().find((client) => client.id === id); } catch (error) { database.exec('ROLLBACK'); throw error; } }
function updateClient(id, data) { const result = database.prepare('UPDATE clientes SET nombre_contacto = ?, correo = ?, telefono = ?, razon_social = ?, tipo_documento = ?, numero_documento = ?, direccion = ?, departamento = ?, provincia = ?, distrito = ? WHERE id = ? AND activo = 1').run(data.name, data.email, data.phone || null, data.company || null, data.documentType || null, data.documentNumber || null, data.address || null, data.department || null, data.province || null, data.district || null, id); return result.changes ? listClients().find((client) => client.id === id) : null; }
function deleteClient(id) { database.exec('BEGIN'); try { const result = database.prepare('UPDATE clientes SET activo = 0 WHERE id = ? AND activo = 1').run(id); if (result.changes) database.prepare("INSERT INTO configuracion_empresa (id, clientes_historicos, fecha_actualizacion) VALUES (1, 1, CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET clientes_historicos = clientes_historicos + 1, fecha_actualizacion = CURRENT_TIMESTAMP").run(); database.exec('COMMIT'); return result.changes > 0; } catch (error) { database.exec('ROLLBACK'); throw error; } }
function createSalesUser(data) { if (database.prepare('SELECT id FROM usuarios WHERE correo = ?').get(data.email)) throw new Error('Ese correo ya pertenece a otra cuenta.'); const id = Number(database.prepare('INSERT INTO usuarios_ventas (nombre, correo, codigo_usuario, telefono, numero_documento, contrasena_hash) VALUES (?, ?, ?, ?, ?, ?)').run(data.name, data.email, data.userCode, data.phone, data.documentNumber, hashPassword(data.temporaryPassword)).lastInsertRowid); return listSalesUsers().find((user) => user.id === id); }
function listSalesUsers() { return database.prepare('SELECT id, nombre AS name, correo AS email, codigo_usuario AS userCode, telefono AS phone, numero_documento AS documentNumber, fecha_creacion AS createdAt FROM usuarios_ventas WHERE activo = 1 ORDER BY id DESC').all(); }
function updateSalesUser(id, data) { if (database.prepare('SELECT id FROM usuarios WHERE correo = ?').get(data.email) || database.prepare('SELECT id FROM usuarios_ventas WHERE (correo = ? OR codigo_usuario = ?) AND id <> ?').get(data.email, data.userCode, id)) throw new Error('El correo o código de usuario ya pertenece a otra cuenta.'); const result = database.prepare('UPDATE usuarios_ventas SET nombre = ?, correo = ?, codigo_usuario = ?, telefono = ?, numero_documento = ? WHERE id = ? AND activo = 1').run(data.name, data.email, data.userCode, data.phone, data.documentNumber, id); return result.changes ? listSalesUsers().find((user) => user.id === id) : null; }
function deleteSalesUser(id) { return database.prepare('UPDATE usuarios_ventas SET activo = 0 WHERE id = ? AND activo = 1').run(id).changes > 0; }
function authenticate(email, password) { const user = database.prepare('SELECT id, id_cliente AS clientId, correo AS email, contrasena_hash AS passwordHash, rol AS role, requiere_cambio_contrasena AS mustChangePassword FROM usuarios WHERE correo = ? AND activo = 1').get(email); if (user && verifyPassword(password, user.passwordHash)) return { id: user.id, clientId: user.clientId, email: user.email, role: user.role, mustChangePassword: Boolean(user.mustChangePassword) }; const salesUser = database.prepare("SELECT id, correo AS email, contrasena_hash AS passwordHash, requiere_cambio_contrasena AS mustChangePassword FROM usuarios_ventas WHERE correo = ? AND activo = 1").get(email); if (!salesUser || !verifyPassword(password, salesUser.passwordHash)) return null; return { id: salesUser.id, clientId: null, email: salesUser.email, role: 'ventas', mustChangePassword: Boolean(salesUser.mustChangePassword) }; }
function changeOwnPassword(userId, role, password) { if (role === 'cliente') return database.prepare('UPDATE usuarios SET contrasena_hash = ?, requiere_cambio_contrasena = 0 WHERE id = ? AND rol = ?').run(hashPassword(password), userId, 'cliente').changes > 0; if (role === 'ventas') return database.prepare('UPDATE usuarios_ventas SET contrasena_hash = ?, requiere_cambio_contrasena = 0 WHERE id = ?').run(hashPassword(password), userId).changes > 0; return false; }
function getClientById(id) { return database.prepare(`SELECT ${clientFields} FROM clientes WHERE id = ? AND activo = 1`).get(id); }
function updateOwnClient(id, data) { const current = getClientById(id); const updated = current && updateClient(id, { ...current, ...data }); if (updated) database.prepare('UPDATE usuarios SET correo = ? WHERE id_cliente = ? AND rol = ?').run(updated.email, id, 'cliente'); return updated; }
function listQuotesByClient(clientId) { return database.prepare("SELECT c.id, c.codigo AS code, c.estado AS status, c.observaciones AS message, (SELECT dc.descripcion_producto FROM detalle_cotizaciones dc WHERE dc.id_cotizacion = c.id LIMIT 1) AS product, c.fecha_creacion AS createdAt FROM cotizaciones c WHERE c.id_cliente = ? ORDER BY c.id DESC").all(clientId); }
function updateOwnQuote(quoteId, clientId, data) { const quote = database.prepare('SELECT id FROM cotizaciones WHERE id = ? AND id_cliente = ? AND estado = ?').get(quoteId, clientId, 'Pendiente'); if (!quote) return null; const product = database.prepare('SELECT id, nombre, precio_referencial, id_unidad_medida FROM productos WHERE nombre = ? AND activo = 1').get(data.product); if (!product) throw new Error('Producto no encontrado.'); database.prepare('UPDATE cotizaciones SET observaciones = ? WHERE id = ?').run(data.message || '', quoteId); database.prepare('UPDATE detalle_cotizaciones SET id_producto = ?, descripcion_producto = ?, precio_unitario = ?, id_unidad_medida = ? WHERE id_cotizacion = ?').run(product.id, product.nombre, product.precio_referencial, product.id_unidad_medida, quoteId); return listQuotesByClient(clientId).find((item) => item.id === quoteId); }
function updateQuoteAdmin(quoteId, data) { const quote = database.prepare('SELECT id_cliente AS clientId FROM cotizaciones WHERE id = ?').get(quoteId); return quote ? updateOwnQuote(quoteId, quote.clientId, data) : null; }
function listOrdersByClient(clientId) { return database.prepare("SELECT p.id, p.codigo AS code, p.estado AS status, p.fecha_creacion AS createdAt, p.fecha_estimada_entrega AS estimatedDeliveryDate, dp.descripcion_producto AS product, dp.cantidad AS quantity, dp.precio_unitario AS price, um.abreviatura AS unit FROM pedidos p LEFT JOIN detalle_pedidos dp ON dp.id_pedido = (SELECT id FROM detalle_pedidos WHERE id_pedido = p.id LIMIT 1) LEFT JOIN unidades_medida um ON um.id = dp.id_unidad_medida WHERE p.id_cliente = ? ORDER BY p.id DESC").all(clientId); }

function initializeData() {
  const unitId = getDefaultUnit();
  if (!database.prepare('SELECT id FROM productos LIMIT 1').get()) {
    const initial = [
      ['PRD-0001', 'Producto Industrial A', 'Línea industrial', 'Solución resistente para operaciones exigentes.', 0, '⚙️'],
      ['PRD-0002', 'Producto Técnico B', 'Línea técnica', 'Diseñado para rendimiento y precisión.', 0, '🔩'],
      ['PRD-0003', 'Producto Profesional C', 'Línea profesional', 'Calidad confiable para tu negocio.', 0, '🧰'],
    ];
    const insert = database.prepare('INSERT INTO productos (codigo, nombre, descripcion, precio_referencial, id_categoria, id_unidad_medida, imagen_url) VALUES (?, ?, ?, ?, ?, ?, ?)');
    initial.forEach(([code, name, category, description, price, image]) => insert.run(code, name, description, price, getOrCreateCategory(category), unitId, image));
  }
  if (!database.prepare('SELECT id FROM pedidos LIMIT 1').get()) {
    const customerId = getOrCreateCustomer('Cliente de ejemplo', 'cliente@ejemplo.com');
    const product = database.prepare('SELECT id, nombre FROM productos LIMIT 1').get();
    const orderId = Number(database.prepare("INSERT INTO pedidos (codigo, id_cliente, estado, fecha_estimada_entrega) VALUES ('PED-1001', ?, 'Pedido en camino', date('now', '+7 days'))").run(customerId).lastInsertRowid);
    database.prepare('INSERT INTO detalle_pedidos (id_pedido, id_producto, descripcion_producto, cantidad, precio_unitario, id_unidad_medida) VALUES (?, ?, ?, 1, 0, ?)').run(orderId, product.id, product.nombre, unitId);
    database.prepare("INSERT INTO historial_estados_pedido (id_pedido, estado, comentario) VALUES (?, 'Pedido en camino', 'Pedido inicial de prueba')").run(orderId);
  }
  if (!database.prepare('SELECT id FROM usuarios WHERE correo = ?').get('admin@empresa.local')) database.prepare('INSERT INTO usuarios (correo, contrasena_hash, rol) VALUES (?, ?, ?)').run('admin@empresa.local', hashPassword('admin123'), 'administracion');
  const customer = database.prepare('SELECT id, correo FROM clientes WHERE correo = ?').get('cliente@ejemplo.com');
  if (customer && !database.prepare('SELECT id FROM usuarios WHERE correo = ?').get(customer.correo)) database.prepare('INSERT INTO usuarios (id_cliente, correo, contrasena_hash, rol) VALUES (?, ?, ?, ?)').run(customer.id, customer.correo, hashPassword('cliente123'), 'cliente');
}
function initializeTimeline() { if (database.prepare('SELECT id FROM hitos_historia LIMIT 1').get()) return; const insert = database.prepare('INSERT INTO hitos_historia (anio, titulo, descripcion) VALUES (?, ?, ?)'); [[2005, 'Inicio de operaciones', 'Comenzamos nuestra trayectoria con el compromiso de brindar soluciones confiables y una atención cercana.'], [2015, 'Crecimiento y consolidación', 'Fortalecimos nuestra presencia, ampliando el catálogo y construyendo relaciones duraderas con nuevos clientes.'], [2022, 'Una nueva etapa', 'Incorporamos nuevas líneas de productos y fortalecimos el equipo comercial para acompañar mejor cada necesidad.'], [2025, 'Transformación digital', 'Dimos un paso hacia una atención más ágil con herramientas digitales para cotizaciones, pedidos y seguimiento.']].forEach((item) => insert.run(...item)); }
function removeDefaultBanners() { database.prepare("DELETE FROM banners_publicitarios WHERE imagen_url IS NULL AND titulo IN ('Soluciones para impulsar tu negocio', 'Atención comercial personalizada', 'Confianza que acompaña tu crecimiento')").run(); }
function initializeAttentionPoints() { if (database.prepare('SELECT id FROM puntos_atencion LIMIT 1').get()) return; const insert = database.prepare('INSERT INTO puntos_atencion (nombre, direccion) VALUES (?, ?)'); [['Tarapoto Tienda', 'Jr. Cabo Alberto Leveau 264, Tarapoto'], ['Tarapoto Tienda', 'Jr. Santa Rosa 481, Tarapoto'], ['Tarapoto Oficina Principal', 'Av. Vía de Evitamiento 1846, Tarapoto'], ['Tarapoto Tienda', 'Av. Illo 601, Tarapoto'], ['Tarapoto Almacén principal', 'Av. Vía de Evitamiento 1590, Tarapoto'], ['Yurimaguas Tienda', 'Jr. José Riera 136, Yurimaguas'], ['Yurimaguas Tienda', 'Calle Monseñor Atanasio Jáuregui 528, Yurimaguas'], ['Yurimaguas Tienda', 'Calle Teniente César López 627, Yurimaguas']].forEach((item) => insert.run(...item)); }

function listCategories() { return database.prepare('SELECT c.id, c.nombre AS name, c.descripcion AS description, c.id_categoria_padre AS parentId, p.nombre AS parentName, c.imagen_url AS image FROM categorias_producto c LEFT JOIN categorias_producto p ON p.id = c.id_categoria_padre WHERE c.activo = 1 ORDER BY COALESCE(c.id_categoria_padre, c.id), c.nombre').all(); }
function getCategory(categoryId) { return database.prepare('SELECT id FROM categorias_producto WHERE id = ? AND activo = 1').get(Number(categoryId)); }
function createCategory(data) { const id = Number(database.prepare('INSERT INTO categorias_producto (nombre, descripcion, id_categoria_padre, imagen_url) VALUES (?, ?, NULL, ?)').run(data.name, data.description || null, data.image || null).lastInsertRowid); return listCategories().find((category) => category.id === id); }
function updateCategory(id, data) { const result = database.prepare('UPDATE categorias_producto SET nombre = ?, descripcion = ?, id_categoria_padre = NULL, imagen_url = ? WHERE id = ? AND activo = 1').run(data.name, data.description || null, data.image || null, id); return result.changes ? listCategories().find((category) => category.id === Number(id)) : null; }
function deleteCategory(id) { if (database.prepare('SELECT id FROM productos WHERE id_categoria = ? AND activo = 1 LIMIT 1').get(id)) throw new Error('No puedes eliminar una categoría que tiene productos asociados. Reasigna o elimina primero sus productos.'); return database.prepare('UPDATE categorias_producto SET activo = 0 WHERE id = ? AND activo = 1').run(id).changes > 0; }
function listProducts() { return database.prepare('SELECT p.id, p.codigo, p.nombre AS name, p.id_categoria AS categoryId, c.nombre AS category, c.id_categoria_padre AS parentCategoryId, cp.nombre AS parentCategory, p.descripcion AS description, p.imagen_url AS image FROM productos p LEFT JOIN categorias_producto c ON c.id = p.id_categoria LEFT JOIN categorias_producto cp ON cp.id = c.id_categoria_padre WHERE p.activo = 1 ORDER BY p.id').all(); }
function createProduct(data) { const categoryId = Number(data.categoryId); if (!getCategory(categoryId)) throw new Error('Selecciona una categoría válida.'); const id = Number(database.prepare('INSERT INTO productos (codigo, nombre, descripcion, id_categoria, id_unidad_medida, imagen_url) VALUES (?, ?, ?, ?, ?, ?)').run(nextCode('PRD', 'productos'), data.name, data.description, categoryId, getDefaultUnit(), data.image || '📦').lastInsertRowid); return listProducts().find((product) => product.id === id); }
function updateProduct(id, data) { const categoryId = Number(data.categoryId); if (!getCategory(categoryId)) throw new Error('Selecciona una categoría válida.'); const result = database.prepare("UPDATE productos SET nombre = ?, descripcion = ?, id_categoria = ?, imagen_url = ?, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ? AND activo = 1").run(data.name, data.description, categoryId, data.image || '📦', id); return result.changes ? listProducts().find((product) => product.id === id) : null; }
function deleteProduct(id) { return database.prepare('UPDATE productos SET activo = 0, fecha_actualizacion = CURRENT_TIMESTAMP WHERE id = ?').run(id).changes > 0; }
function createQuote(data) { const customerId = getOrCreateCustomer(data.name, data.email); const product = database.prepare('SELECT id, nombre, precio_referencial, id_unidad_medida FROM productos WHERE nombre = ? AND activo = 1').get(data.product); if (!product) throw new Error('Producto no encontrado.'); const id = Number(database.prepare('INSERT INTO cotizaciones (codigo, id_cliente, observaciones) VALUES (?, ?, ?)').run(nextCode('COT', 'cotizaciones'), customerId, data.message || '').lastInsertRowid); database.prepare('INSERT INTO detalle_cotizaciones (id_cotizacion, id_producto, descripcion_producto, cantidad, precio_unitario, id_unidad_medida) VALUES (?, ?, ?, 1, ?, ?)').run(id, product.id, product.nombre, product.precio_referencial, product.id_unidad_medida); return listQuotes().find((quote) => quote.id === id); }
function listQuotes() { return database.prepare("SELECT c.id, c.codigo AS code, cl.nombre_contacto AS name, cl.correo AS email, c.observaciones AS message, (SELECT dc.descripcion_producto FROM detalle_cotizaciones dc WHERE dc.id_cotizacion = c.id LIMIT 1) AS product, (SELECT p.codigo FROM pedidos p WHERE p.id_cotizacion = c.id LIMIT 1) AS orderCode FROM cotizaciones c JOIN clientes cl ON cl.id = c.id_cliente ORDER BY c.id DESC").all(); }
function createOrderFromQuote(quoteId, data) { const quote = database.prepare('SELECT id, codigo, id_cliente FROM cotizaciones WHERE id = ?').get(quoteId); if (!quote) throw new Error('Cotización no encontrada.'); const existing = database.prepare('SELECT codigo FROM pedidos WHERE id_cotizacion = ?').get(quoteId); if (existing) throw new Error(`Esta cotización ya está asociada al pedido ${existing.codigo}.`); const product = database.prepare('SELECT id, nombre FROM productos WHERE nombre = ? AND activo = 1').get(data.product); if (!product) throw new Error('Selecciona un producto válido.'); const unitId = getUnitByAbbreviation(data.unit); const orderId = Number(database.prepare("INSERT INTO pedidos (codigo, id_cliente, id_cotizacion, estado, fecha_estimada_entrega) VALUES (?, ?, ?, 'Pedido en curso', ?)").run(nextCode('PED', 'pedidos'), quote.id_cliente, quote.id, data.estimatedDeliveryDate).lastInsertRowid); database.prepare('INSERT INTO detalle_pedidos (id_pedido, id_producto, descripcion_producto, cantidad, precio_unitario, id_unidad_medida) VALUES (?, ?, ?, ?, ?, ?)').run(orderId, product.id, product.nombre, Number(data.quantity), Number(data.price), unitId); database.prepare("INSERT INTO historial_estados_pedido (id_pedido, estado, comentario) VALUES (?, 'Pedido en curso', 'Pedido creado desde cotización')").run(orderId); return getOrderById(orderId); }
function listOrders() { return database.prepare("SELECT p.id, p.codigo AS code, cl.nombre_contacto AS customer, cl.correo AS customerEmail, p.estado AS status, p.fecha_creacion AS createdAt, p.fecha_estimada_entrega AS estimatedDeliveryDate, dp.descripcion_producto AS product, dp.cantidad AS quantity, dp.precio_unitario AS price, um.abreviatura AS unit, c.codigo AS quoteCode, p.fecha_creacion AS updatedAt FROM pedidos p JOIN clientes cl ON cl.id = p.id_cliente LEFT JOIN detalle_pedidos dp ON dp.id_pedido = (SELECT id FROM detalle_pedidos WHERE id_pedido = p.id LIMIT 1) LEFT JOIN unidades_medida um ON um.id = dp.id_unidad_medida LEFT JOIN cotizaciones c ON c.id = p.id_cotizacion ORDER BY p.id DESC").all(); }
function getOrderById(id) { return listOrders().find((order) => order.id === id); }
function getOrderByCode(code) { return listOrders().find((order) => order.code === code); }
function updateOrderStatus(code, status) { const order = database.prepare('SELECT id FROM pedidos WHERE codigo = ?').get(code); if (!order) return null; database.prepare('UPDATE pedidos SET estado = ? WHERE id = ?').run(status, order.id); database.prepare('INSERT INTO historial_estados_pedido (id_pedido, estado) VALUES (?, ?)').run(order.id, status); return getOrderById(order.id); }
function getAnalyticsSnapshot() {
  const total = (statement) => Number(database.prepare(statement).get().total || 0);
  const distribution = (statement) => database.prepare(statement).all();
  return {
    totals: {
      clients: total('SELECT COUNT(*) AS total FROM clientes WHERE activo = 1'),
      products: total('SELECT COUNT(*) AS total FROM productos WHERE activo = 1'),
      quotes: total('SELECT COUNT(*) AS total FROM cotizaciones'),
      orders: total('SELECT COUNT(*) AS total FROM pedidos'),
    },
    productsByCategory: distribution("SELECT c.nombre AS label, COUNT(p.id) AS value FROM categorias_producto c LEFT JOIN productos p ON p.id_categoria = c.id AND p.activo = 1 WHERE c.activo = 1 GROUP BY c.id, c.nombre ORDER BY value DESC, label"),
    clientsByDepartment: distribution("SELECT COALESCE(NULLIF(departamento, ''), 'Sin registrar') AS label, COUNT(*) AS value FROM clientes WHERE activo = 1 GROUP BY COALESCE(NULLIF(departamento, ''), 'Sin registrar') ORDER BY value DESC, label"),
    quotesByStatus: distribution('SELECT estado AS label, COUNT(*) AS value FROM cotizaciones GROUP BY estado ORDER BY value DESC, label'),
    ordersByStatus: distribution('SELECT estado AS label, COUNT(*) AS value FROM pedidos GROUP BY estado ORDER BY value DESC, label'),
    quotesByProduct: distribution("SELECT dc.descripcion_producto AS label, COUNT(*) AS value FROM detalle_cotizaciones dc JOIN cotizaciones c ON c.id = dc.id_cotizacion GROUP BY dc.descripcion_producto ORDER BY value DESC, label LIMIT 8"),
    monthlyGrowth: distribution("SELECT strftime('%Y-%m', fecha_creacion) AS month, 'Cotizaciones' AS label, COUNT(*) AS value FROM cotizaciones WHERE fecha_creacion >= date('now', '-5 months', 'start of month') GROUP BY month UNION ALL SELECT strftime('%Y-%m', fecha_creacion) AS month, 'Pedidos' AS label, COUNT(*) AS value FROM pedidos WHERE fecha_creacion >= date('now', '-5 months', 'start of month') GROUP BY month ORDER BY month, label"),
  };
}

configureOrderUnits();
initializeData();
initializeTimeline();
removeDefaultBanners();
initializeAttentionPoints();
module.exports = { listProducts, listCategories, createCategory, updateCategory, deleteCategory, listUnits, getCompanySettings, updateContactNumbers, updateSocialNetworks, updateHistoricalClients, getKpis, listAdditionalKpis, createAdditionalKpi, deleteAdditionalKpi, listTimelineItems, createTimelineItem, updateTimelineItem, deleteTimelineItem, listBanners, listBannersAdmin, createBanner, updateBanner, deleteBanner, listCommercialPartners, createCommercialPartner, updateCommercialPartner, deleteCommercialPartner, listAttentionPoints, createAttentionPoint, updateAttentionPoint, deleteAttentionPoint, createProduct, updateProduct, deleteProduct, listClients, createClient, updateClient, deleteClient, createSalesUser, listSalesUsers, updateSalesUser, deleteSalesUser, authenticate, changeOwnPassword, getClientById, updateOwnClient, listQuotesByClient, updateOwnQuote, updateQuoteAdmin, listOrdersByClient, createQuote, listQuotes, createOrderFromQuote, listOrders, getOrderByCode, updateOrderStatus, getAnalyticsSnapshot };
